import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "core.settings")
django.setup()

from django.db import transaction
from tracker.models import MasterFinancialCategory

# Data arrays stay compact and readable
BALANCESHEET_SOURCE_ROWS = [
    (
        1655,
        "Assets",
        "Gold & Investments",
        "AG Asset",
        "Investments",
        "AG Asset",
        False,
    ),
    (
        1656,
        "Assets",
        "Bank Transfers",
        "Bank Transfer",
        "Banking",
        "Bank Charge",
        False,
    ),
    (
        1657,
        "Assets",
        "Opening Balance",
        "Brought Forward",
        "Account Balances",
        "Brought Forward",
        False,
    ),
    (
        1658,
        "Assets",
        "Opening Balance",
        "Opening Balance",
        "Account Balances",
        "Opening Balance",
        False,
    ),
    (
        1659,
        "Income",
        "Property & Rental Income",
        "City Plaza (Rent)",
        "Real Estate",
        "City Plaza (Rent)",
        False,
    ),
    (
        1660,
        "Assets",
        "Fixed Deposits",
        "FD Closure",
        "Investments",
        "FD Closure",
        False,
    ),
    (1661, "Assets", "Fixed Deposits", "FD-Closed", "Investments", "FD-Closed", False),
    (1662, "Assets", "Fixed Deposits", "FD", "Investments", "FD", False),
    (1663, "Assets", "Fixed Deposits", "FD-Income", "Investments", "FD-Income", False),
    (1664, "Assets", "Fixed Deposits", "FD-Opened", "Investments", "FD-Opened", False),
    (1665, "Assets", "Bank Balances", "Fed", "Banking", "Fed", False),
    (
        1666,
        "Assets",
        "Loans & Repayments- Transfer",
        "Loan Repay",
        "Loans",
        "Loan Repay",
        False,
    ),
    (
        1667,
        "Assets",
        "Reverse",
        "Locker Rent Reverse",
        "Adjustments",
        "Locker Rent Reverse",
        False,
    ),
    (1668, "Assets", "Gold & Investments", "MF", "Investments", "MF", False),
    (1669, "Assets", "Gold & Investments", "MF", "Investments", "MF", False),
    (1670, "Assets", "Investment", "NPS", "Investments", "NPS", False),
    (1671, "Assets", "Payout", "NPS", "Payments", "NPS", False),
    (1672, "Assets", "Reverse", "Reverse", "Adjustments", "Reverse", False),
    (1673, "Assets", "Bank Balances", "SBI", "Banking", "SBI", False),
    (1674, "Assets", "Bank Balances", "SBI-NRO-9418", "Banking", "SBI-NRO-9418", False),
    (1675, "Assets", "Self Account Transfer", "Self", "Transfers", "Self", False),
    (1676, "Assets", "Self Account Transfer", "Self", "Transfers", "Self", False),
    (1677, "Assets", "Bank Balances", "SIB<--", "Banking", "SIB<--", False),
    (1678, "Assets", "Bank Transfers", "SIB", "Banking", "SIB<--", False),
    (1679, "Assets", "Bank Balances", "SIB", "Banking", "SIB", False),
    (1680, "Assets", "Bank Account", "SIB-NRE-49", "Banking", "SIB-NRE-49", False),
    (1681, "Assets", "Bank Balances", "SIB-NRO-49", "Banking", "SIB-NRO-49", False),
    (1682, "Assets", "Bank Balances", "SIB-NRO-60", "Banking", "SIB-NRO-60", False),
    (1683, "Assets", "Bank Balances", "SIB-NRO-81", "Banking", "SIB-NRO-81", False),
    (
        1684,
        "Income",
        "Property & Rental Income",
        "SUN Medanta (Rent)",
        "Real Estate",
        "SUN Medanta (Rent)",
        False,
    ),
    (
        1685,
        "Current Assets",
        "Prepaid Expenses",
        "Health Insurance",
        "Budgeting",
        "Health Insurance",
        False,
    ),
    (1686, "Assets", "Bank Balances", "SIB<->SIB", "Banking", "SIB<->SIB", False),
    (
        1687,
        "Expenses",
        "Gold & Investments",
        "AG Asset-Reverse",
        "Investments",
        "AG Asset",
        True,
    ),
    (
        1688,
        "Expenses",
        "Gold & Investments",
        "AG Asset",
        "Investments",
        "AG Asset",
        True,
    ),
    (
        1689,
        "Expenses",
        "Insurance Premiums",
        "Ageas-Insurance",
        "Insurance",
        "Ageas-Insurance",
        True,
    ),
    (1690, "Expenses", "Cellular", "Vodafone", "Utilities", "Vodafone", True),
    (1691, "Expenses", "Cellular", "Airtel", "Utilities", "Airtel", True),
    (1692, "Expenses", "LAW", "Alfas-vineeth", "Legal", "Alfas-vineeth", True),
    (1693, "Expenses", "Business Expenses", "BDS", "Business", "BDS", True),
    (1694, "Expenses", "Donation", "Charity", "Charity", "Charity", True),
    (
        1695,
        "Expenses",
        "City Plaza Expense",
        "City Plaza (Expense)",
        "Personal Expense",
        "City Plaza (Expense)",
        True,
    ),
    (
        1696,
        "Expenses",
        "Rent & Maintenance",
        "City Plaza (Maintenance)",
        "Real Estate",
        "City Plaza (Maintenance)",
        True,
    ),
    (1697, "Expenses", "Business Expenses", "CSC", "Business", "CSC", True),
    (1698, "Expenses", "Education", "Education", "Education", "Education", True),
    (1699, "Expenses", "Fixed Deposits", "FD", "Investments", "FD", True),
    (1700, "Expenses", "Bank Transfers", "FED->SBI", "Banking", "FED->SBI", True),
    (1701, "Expenses", "Bank Transfers", "Fed", "Banking", "Fed", True),
    (1702, "Expenses", "Cloths", "Garments", "Shopping", "Garments", True),
    (1703, "Expenses", "Business Expenses", "GODADDY", "Business", "GODADDY", True),
    (1704, "Expenses", "Business Expenses", "Google", "Business", "Google", True),
    (
        1705,
        "Expenses",
        "Insurance Premiums",
        "HDFC Life",
        "Insurance",
        "HDFC Life",
        True,
    ),
    (1706, "Expenses", "Insurance Premiums", "LIC", "Insurance", "LIC", True),
    (1707, "Expenses", "Business Expenses", "Microsoft", "Business", "Microsoft", True),
    (
        1708,
        "Expenses",
        "Penstion Premiums",
        "national pension scheme",
        "#N/A",
        "national pension scheme",
        True,
    ),
    (1709, "Expenses", "Bank Transfers", "SBI->FED", "Banking", "SBI->FED", True),
    (1710, "Expenses", "Bank Transfers", "SBI", "Banking", "SBI", True),
    (1711, "Expenses", "Insurance Premiums", "SBI-Life", "Insurance", "SBI-Life", True),
    (
        1712,
        "Expenses",
        "Other Comprehensive Expense",
        "ShareMarket",
        "Miscellaneous",
        "ShareMarket",
        True,
    ),
    (1713, "Expenses", "Bank Account", "SIB-NRE-4250", "Banking", "SIB-NRO-4250", True),
    (1714, "Expenses", "Bank Account", "SIB-NRE-49", "Banking", "SIB-NRE-49", True),
    (1715, "Expenses", "Bank Account", "SIB-NRO-81", "Banking", "SIB-NRO-81", True),
    (
        1716,
        "Expenses",
        "Rent & Maintenance",
        "SUN Medanta (Maintenance)",
        "Real Estate",
        "SUN Medanta (Maintenance)",
        True,
    ),
    (1717, "Expenses", "Taxes", "TAX", "Taxes", "TAX", True),
    (1718, "Expenses", "Donation", "Temple", "Charity", "Temple", True),
    (1719, "Expenses", "LAW", "Vineeth", "Legal", "Vineeth", True),
    (
        1720,
        "Expenses",
        "Vehicle Insurance",
        "XUV Insurance",
        "Insurance",
        "XUV Insurance",
        True,
    ),
    (
        1721,
        "Expenses",
        "Vehicle Maintenance",
        "XUV Tyre",
        "Transport",
        "XUV Tyre",
        True,
    ),
    (1722, "Expenses", "Rent & Maintenance", "Sun Homes", "Real Estate", "Venus", True),
    (1723, "Expenses", "Rent & Maintenance", "Venus", "Real Estate", "Venus", True),
    (
        1724,
        "Income",
        "Insurance Payouts",
        "Ageas-Insurance",
        "Insurance",
        "Ageas-Insurance",
        False,
    ),
    (
        1725,
        "Income",
        "Family & Friends Transfers (Received)",
        "Arun",
        "Personal Transfers",
        "Arun",
        False,
    ),
    (1726, "Income", "Business Income", "BDS", "Business", "BDS", False),
    (1727, "Income", "Rental Income", "City Plaza", "Real Estate", "City Plaza", False),
    (1728, "Income", "Bank Transfers", "FED->SBI", "Banking", "FED->SBI", False),
    (
        1729,
        "Income",
        "Salary & Business Income",
        "FT Income",
        "Income",
        "FT Income",
        False,
    ),
    (
        1730,
        "Income",
        "Family & Friends Transfers (Received)",
        "Gopinath",
        "Personal Transfers",
        "Gopinath",
        False,
    ),
    (1731, "Income", "Insurance Payouts", "HDFC Life", "Insurance", "HDFC Life", False),
    (1732, "Income", "Salary & Business Income", "Int FD", "Income", "Int FD", False),
    (
        1733,
        "Income",
        "Salary & Business Income",
        "Int Income",
        "Income",
        "Int Income",
        False,
    ),
    (
        1734,
        "Income",
        "Salary & Business Income",
        "Interest",
        "Income",
        "Interest",
        False,
    ),
    (1735, "Income", "Insurance Payouts", "LIC", "Insurance", "LIC", False),
    (1736, "Income", "Business Income", "Microsoft", "Business", "Microsoft", False),
    (
        1737,
        "Income",
        "Pension Payouts",
        "national pension scheme",
        "Retirement",
        "national pension scheme",
        False,
    ),
    (1738, "Income", "Reverse", "PVR", "Adjustments", "PVR", False),
    (1739, "Income", "Salary & Business Income", "SALARY", "Income", "SALARY", False),
    (1740, "Income", "Bank Transfers", "SBI->FED", "Banking", "SBI->FED", False),
    (1741, "Income", "Insurance Payouts", "SBI-Life", "Insurance", "SBI-Life", False),
    (
        1742,
        "Income",
        "Family & Friends Transfers (Received)",
        "Sudheer",
        "Personal Transfers",
        "Sudheer",
        False,
    ),
    (
        1743,
        "Income",
        "Family & Friends Transfers (Received)",
        "Sujith S",
        "Personal Transfers",
        "Sujith S",
        False,
    ),
    (
        1744,
        "Income",
        "Rental Income",
        "SUN Medanta",
        "Real Estate",
        "SUN Medanta",
        False,
    ),
    (1745, "Income", "UPI Transfers", "UPI", "Transfers", "UPI", False),
    (1746, "Income", "LAW", "Vineeth", "Legal", "Vineeth", False),
    (1747, "Income", "Fixed Deposits", "To FD", "Investments", "To FD", False),
    (
        1748,
        "Liabilities",
        "Payables",
        "Account Transfer",
        "Liabilities",
        "Account Transfer",
        False,
    ),
    (
        1749,
        "Liabilities",
        "Bank Charges & Fees",
        "Bank AMC",
        "Banking",
        "Bank AMC",
        False,
    ),
    (
        1750,
        "Liabilities",
        "Bank Charges & Fees",
        "Bank Charge",
        "Banking",
        "Bank Charge",
        False,
    ),
    (
        1751,
        "Liabilities",
        "Bank Charges & Fees",
        "Bankk Fees",
        "Banking",
        "Bankk Fees",
        False,
    ),
    (
        1752,
        "Liabilities",
        "Loans & Repayments",
        "Loan Repay",
        "Loans",
        "Loan Repay",
        False,
    ),
    (
        1753,
        "Liabilities",
        "Bank Charges & Fees",
        "Locker Rent",
        "Banking",
        "Locker Rent",
        False,
    ),
    (1754, "Liabilities", "Reverse", "Reverse", "Adjustments", "Reverse", False),
    (
        1755,
        "OCI",
        "Other Comprehensive Income",
        "ShareMarket",
        "Miscellaneous",
        "ShareMarket",
        False,
    ),
    (
        1756,
        "Other Assets",
        "Bank Account",
        "Err-Uncategorized",
        "Banking",
        "Err-Uncategorized",
        False,
    ),
    (
        1757,
        "Transfers",
        "Cash Transactions",
        "ATM-Cash",
        "Cash Flow",
        "ATM-Cash",
        False,
    ),
    (
        1758,
        "Transfers",
        "Bank Transfers",
        "Bank Transfer",
        "Banking",
        "Bank Transfer",
        False,
    ),
    (
        1759,
        "Transfers",
        "Cash Transactions",
        "Cash Cheque",
        "Cash Flow",
        "Cash Cheque",
        False,
    ),
    (
        1760,
        "Transfers",
        "Cash Transactions",
        "Cash Withdrawal",
        "Cash Flow",
        "Cash Withdrawal",
        False,
    ),
    (1761, "Transfers", "Bank Transfers", "FD-Closed", "Banking", "FD-Closed", False),
    (
        1762,
        "Transfers",
        "Bank Transfers",
        "FED-Inter-TRNS",
        "Banking",
        "FED-Inter-TRNS",
        False,
    ),
    (
        1763,
        "Transfers",
        "Bank Transfers",
        "FED-Inter-TRNS",
        "Banking",
        "FED-Inter-TRNS",
        False,
    ),
    (
        1764,
        "Transfers",
        "Bank Transfers",
        "FED-NRO-1050",
        "Banking",
        "FED-NRO-1050",
        False,
    ),
    (
        1765,
        "Transfers",
        "Bank Transfers",
        "FED-NRO-1050",
        "Banking",
        "FED-NRO-1050",
        False,
    ),
    (1766, "Transfers", "Bank Transfers", "SBI->SIB", "Banking", "SBI->SIB", False),
    (1767, "Transfers", "Bank Transfers", "SIB<->SIB", "Banking", "SBI->SIB", False),
    (1768, "Transfers", "To FD", "To FD", "Investments", "To FD", False),
    (
        1769,
        "Transfers",
        "Bank Transfers",
        "SBI-NRE-4250",
        "Banking",
        "SBI-NRE-4250",
        False,
    ),
    (
        1770,
        "Transfers",
        "Bank Transfers",
        "SBI-NRO-9418",
        "Banking",
        "To SBI NRO 9418",
        False,
    ),
    (1771, "Transfers", "UPI Transfers", "UPI", "Transfers", "UPI", False),
    (
        1772,
        "Transfers",
        "International Transfers",
        "USD Transfer",
        "Transfers",
        "USD Transfer",
        False,
    ),
    (1773, "Assets", "Suspense", "Suspense", "Uncategorized", "Suspense-E-I", False),
    (
        1774,
        "Assets",
        "Suspense",
        "Uncategorized-Cr",
        "Uncategorized",
        "Uncategorized-Cr-I",
        False,
    ),
    (
        1775,
        "Assets",
        "Suspense",
        "Uncategorized-Dr",
        "Uncategorized",
        "Uncategorized-Dr-E",
        False,
    ),
    (1776, "Expenses", "Shopping", "Amazon", "Shopping", "Amazon", True),
    (
        1777,
        "Expenses",
        "Entertainment",
        "Amazon-Prime",
        "Leisure",
        "Amazon-Prime",
        True,
    ),
    (
        1778,
        "Expenses",
        "Family & Friends (Given)",
        "Arun",
        "Personal Transfers",
        "Arun",
        True,
    ),
    (
        1779,
        "Expenses",
        "Travel & Transport",
        "Attingal Parking",
        "Transport",
        "Attingal Parking",
        True,
    ),
    (1780, "Expenses", "Shopping", "Bazaar-Shop", "Shopping", "Bazaar-Shop", True),
    (1781, "Expenses", "Family & Personal", "Beena", "Personal Expense", "Beena", True),
    (
        1782,
        "Expenses",
        "Entertainment",
        "Book my Show",
        "Leisure",
        "Book my Show",
        True,
    ),
    (1783, "Expenses", "Food & Beverages", "Coffe", "Dining", "Coffe", True),
    (1784, "Expenses", "Food & Beverages", "Costa", "Dining", "Costa", True),
    (1785, "Expenses", "Household", "Crossword", "Household", "Crossword", True),
    (
        1786,
        "Expenses",
        "Entertainment",
        "Disney Hotstar",
        "Leisure",
        "Disney Hotstar",
        True,
    ),
    (1787, "Expenses", "Groceries", "Fish", "Household", "Fish", True),
    (1788, "Expenses", "Travel & Transport", "FUEL", "Transport", "FUEL", True),
    (1789, "Expenses", "Travel & Transport", "GAS", "Transport", "GAS", True),
    (
        1790,
        "Expenses",
        "Household",
        "Hardwares & EE",
        "Household",
        "Hardwares & EE",
        True,
    ),
    (1791, "Expenses", "Medical Expenses", "Hospital", "Healthcare", "Hospital", True),
    (
        1792,
        "Expenses",
        "Family & Personal",
        "Hospital-M&D",
        "Personal Expense",
        "Hospital-M&D",
        True,
    ),
    (
        1793,
        "Expenses",
        "Personal Expense",
        "iCloud",
        "Personal Expense",
        "iCloud",
        True,
    ),
    (1794, "Expenses", "Utilities (TV & Internet)", "JIO", "Utilities", "JIO", True),
    (1795, "Expenses", "Utilities", "KSEB", "Utilities", "KSEB", True),
    (1796, "Expenses", "Travel & Transport", "KSRTC", "Transport", "KSRTC", True),
    (1797, "Expenses", "Utilities", "KSSTM", "Utilities", "KSSTM", True),
    (1798, "Expenses", "Utilities", "KWAT", "Utilities", "KWAT", True),
    (
        1799,
        "Expenses",
        "Travel & Transport",
        "Lulu Parking",
        "Transport",
        "Lulu Parking",
        True,
    ),
    (1800, "Expenses", "Shopping", "LULU", "Shopping", "LULU", True),
    (1801, "Expenses", "Groceries", "Margin free", "Household", "Margin free", True),
    (
        1802,
        "Expenses",
        "Family & Personal",
        "Mom & Dad",
        "Personal Expense",
        "Mom & Dad",
        True,
    ),
    (1803, "Expenses", "Shopping", "MORE", "Shopping", "MORE", True),
    (1804, "Expenses", "Shopping", "MOT", "Shopping", "MOT", True),
    (1805, "Expenses", "Entertainment", "Netflix", "Leisure", "Netflix", True),
    (
        1806,
        "Expenses",
        "Personal Expense",
        "Personal Exp",
        "Personal Expense",
        "Personal Exp",
        True,
    ),
    (1807, "Expenses", "Medicines", "Pharmacy", "Healthcare", "Pharmacy", True),
    (1808, "Expenses", "POS Purchase", "POS", "Shopping", "POS", True),
    (1809, "Expenses", "Household", "Pothy", "Household", "Pothy", True),
    (1810, "Expenses", "Household", "Premier", "Household", "Premier", True),
    (1811, "Expenses", "Entertainment", "PVR", "Leisure", "PVR", True),
    (1812, "Expenses", "Groceries", "Ramachandran", "Household", "Ramachandran", True),
    (
        1813,
        "Expenses",
        "Food & Beverages",
        "Restaurants",
        "Dining",
        "Restaurants",
        True,
    ),
    (1814, "Expenses", "Groceries", "Shopping", "Household", "Shopping", True),
    (
        1815,
        "Expenses",
        "Family & Friends (Given)",
        "Sujith S",
        "Personal Transfers",
        "Sujith S",
        True,
    ),
    (1816, "Expenses", "Shopping", "Reliance", "Shopping", "MOT", True),
    (1817, "Expenses", "Shopping", "Sun Store", "Shopping", "Sun Store", True),
    (1818, "Expenses", "Food & Beverages", "Swiggy", "Dining", "Swiggy", True),
    (
        1819,
        "Income",
        "Travel & Transport",
        "Transportation",
        "Transport",
        "Transportation",
        False,
    ),
    (
        1820,
        "Expenses",
        "Travel & Transport",
        "Transportation",
        "Transport",
        "Transportation",
        True,
    ),
    (1821, "Expenses", "Groceries", "Vegetable", "Household", "Vegetable", True),
    (1822, "Expenses", "Family & Personal", "Wife", "Personal Expense", "Wife", True),
    (1823, "Expenses", "Food & Beverages", "Zomato", "Dining", "Zomato", True),
    (1824, "Income", "Family & Personal", "Beena", "Personal Expense", "Beena", False),
    (1825, "Income", "Family & Personal", "Wife", "Personal Expense", "Wife", False),
    (
        1826,
        "Assets",
        "Suspense",
        "Suspense Expense Account",
        "Uncategorized",
        "Suspense-E-I",
        False,
    ),
    (
        1827,
        "Liabilities",
        "Suspense",
        "Suspense",
        "Uncategorized",
        "Suspense-I-E",
        False,
    ),
    (
        1828,
        "Transfers",
        "Family & Friends (Given)",
        "Gopinath",
        "Personal Transfers",
        "Gopinath",
        False,
    ),
    (
        1829,
        "Transfers",
        "Family & Friends (Given)",
        "Sudheer",
        "Personal Transfers",
        "Sudheer",
        False,
    ),
]

KNOWNDEFAULT_SOURCE_ROWS = [
    (1709, "Account Transfer", "Transfer", "wdl tfr", ""),
    (1710, "AG Asset", "Jwellery", "Bhima", ""),
    (1711, "AG Asset", "Jwellery", "bhima jewellers and diamonds", "upi"),
    (1712, "AG Asset", "Jwellery", "bhima jewellery", "upi"),
    (1713, "AG Asset", "Jwellery", "joyalukkas", ""),
    (1714, "AG Asset", "Income", "jwellery", ""),
    (1715, "AG Asset", "Jwellery", "Kalyan", ""),
    (1716, "AG Asset-Reverse", "Expense", "tfr:wrong entry chq 334293", ""),
    (1717, "Ageas-Insurance", "Expense", "ageasfddc", ""),
    (1718, "Airtel", "Bill", "airtel payments", "upi"),
    (1719, "Alfas-vineeth", "Transfer", "alfaslegal@", "upi"),
    (1720, "Amazon", "Shopping", "amazon", "UPI"),
    (1721, "Amazon", "Shopping", "amazon india", "UPI"),
    (1722, "Amazon", "Shopping", "amazon pay", "upi"),
    (1723, "Amazon", "Shopping", "Amazon Seller", "wdl tfr"),
    (1724, "Amazon", "Shopping", "amazonupi", "upi"),
    (1725, "Amazon", "Shopping", "amznplpvrv", "upi"),
    (1726, "Amazon Video", "Entertainment", "amazon prime", "upi"),
    (1727, "Arun", "Expense", "barat", "upiout"),
    (1728, "Arun", "Expense", "barat k gopinath", "UPI"),
    (1729, "Arun", "Expense", "baratkgopinath1998", "UPI"),
    (1730, "Arun", "Expense", "redteam hacker academy", "UPI"),
    (1731, "ATM-Cash", "Cash Withdrawal", "atm wdl", ""),
    (1732, "Attingal Parking", "Expense", "car parking", ""),
    (1733, "Attingal Parking", "Expense", "car parking", ""),
    (1734, "Bank AMC", "Fees", "amc", ""),
    (1735, "Bank Charge", "Fees", "cash wdl service", ""),
    (1736, "Bank Charge", "Fees", "charges for rtgs", ""),
    (1737, "Bank Charge", "Fees", "chrg", ""),
    (1738, "Bank Charge", "Fees", "chrg/imps", ""),
    (1739, "Bank Charge", "Fees", "chrg/min bal", ""),
    (1740, "Bank Charge", "Fees", "commission", ""),
    (1741, "Bank Charge", "Fees", "debit card amc", ""),
    (1742, "Bank Charge", "Fees", "debit card amc", ""),
    (1743, "Bank Charge", "Fees", "IMPS Charges", ""),
    (1744, "Bank Charge", "Fees", "IMPS Charges:", ""),
    (1745, "Bank Charge", "Fees", "insufficient bal", "wdl tfr"),
    (1746, "Bank Charge", "Fees", "mandate fail chrg", ""),
    (1747, "Bank Charge", "Fees", "min bal", ""),
    (1748, "Bank Charge", "Expense", "minimum balance charges", ""),
    (1749, "Bank Charge", "Expense", "sms charges", ""),
    (1750, "Bank Charge", "Fees", "wdl  service", ""),
    (1751, "Bank Charge", "Fees", "wdlservice", ""),
    (1752, "Bank Transfer", "Trasnfer", "dep tfr", ""),
    (1753, "Bazaar-Shop", "Shopping", "bazaar pvt lt", "UPI"),
    (1754, "BDS", "Expense", "indiafilings pvt ltd", "imps"),
    (1755, "Beena", "Expense", "beena thingal", "wdl tfr"),
    (1756, "Beena", "Expense", "beena thingal", ""),
    (1757, "Beena", "Income", "CASH DEPOSIT BEENA", ""),
    (1758, "Beena", "Expense", "ms. beena thingal", ""),
    (1759, "Book my Show", "Expense", "bigtree entertainment", "wdl tfr"),
    (1760, "Book my Show", "Expense", "bookmyshow", "upi"),
    (1761, "Brought Forward", "Brought Forward", "Brought Forword", ""),
    (1762, "Cash Cheque", "Cash Expense", "cas cash", ""),
    (1763, "Cash Cheque", "Cheque Expense", "cas chq", ""),
    (1764, "Cash Withdrawal", "Expense", "to atm", ""),
    (1771, "City Plaza (Expense)", "Expense", "city plaza", "upi"),
    (1772, "City Plaza (Maintenance)", "Expense", "331114505882", "mob"),
    (1773, "City Plaza (Maintenance)", "Expense", "boban  george/upi", "upi"),
    (1774, "City Plaza (Maintenance)", "Expense", "c m harshan/upi", "upi"),
    (1775, "City Plaza (Maintenance)", "Expense", "city plaza flat owners  asso", ""),
    (1776, "City Plaza (Rent)", "Transfer", "NEENU JOSEPH", "payment from p"),
    (1777, "Coffe", "Expense", "haleelulla  j", "upi"),
    (1778, "Costa", "Expense", "costa", "upi"),
    (1779, "Crossword", "Shopping", "crossword  lulu", "upi"),
    (1780, "CSC", "Expense", "/csc e governance india limit", ""),
    (1781, "CSC", "Expense", "CSC", ""),
    (1782, "Disney Hotstar", "Bill", "disney hotsta", "UPI"),
    (1783, "Education", "Education", "Jain Trust", "upi"),
    (1784, "Education", "Education", "jain trust", "wdl tfr"),
    (1785, "Education", "Education", "jain university", "upi"),
    (1786, "Education", "Education", "jain university/jainuniversi", "upi"),
    (1787, "Education", "Education", "jainonline", "upi"),
    (1788, "Education", "Education", "jainuniversi", "upi"),
    (1789, "FD", "Income", "21782300003181", ""),
    (1790, "FD Closure", "Income", "closure proceeds", ""),
    (1791, "FD Closure", "Income", "dep tfrfor personal use", "baiju suseelan nat"),
    (1792, "FD-Closed", "Income", "21782300003173", ""),
    (1793, "FD-Closed", "Income", "21782400000236", ""),
    (1794, "FD-Closed", "Income", "21782400000244", ""),
    (1795, "FD-Closed", "Income", "21782400000251", ""),
    (1796, "FD-Closed", "Income", "21782400000699", ""),
    (1797, "FD-Income", "Income", "[21782400000269] :", ""),
    (1798, "FD-Income", "Income", "[21782400000277] :", ""),
    (1799, "FD-Income", "Income", "[21782400000285]", ""),
    (1800, "FD-Income", "Income", "[21782400000699] :", ""),
    (1801, "FD-Income", "Income", "[21782400000707] :", ""),
    (1802, "FD-Income", "Income", "[21782400000715] :", ""),
    (1803, "FD-Opened", "Income", "21782400000269", ""),
    (1804, "Fed", "BANK", "FDRL", ""),
    (1805, "Fed", "BANK", "Federal", ""),
    (1806, "FED->SBI", "Transfer", "FDRLR52023100300751836", ""),
    (1807, "FED-Inter-TRNS", "Transfer", "mb ftb", ""),
    (1808, "FED-Inter-TRNS", "Transfer", "mb fto", ""),
    (1809, "FED-NRO-1050", "Transfer", "fdrl-xx050", "wdl tfr"),
    (1810, "FED-NRO-1050", "Transfer", "SBONR", ""),
    (1811, "FT Income", "Income", "FT IMPS", ""),
    (1812, "FUEL", "Fuel", "fuels", ""),
    (1813, "FUEL", "Expense", "NAGARAJAN AND SONS", ""),
    (1814, "FUEL", "Expense", "nagarajan s", ""),
    (1815, "Garments", "Shopping", "garments", "upi"),
    (1816, "GAS", "Expense", "Gas", ""),
    (1817, "GODADDY", "Expense", "godaddy", ""),
    (1818, "Google", "Business", "Google", ""),
    (1819, "Gopinath", "Expense", "gkinter2000-1@", ""),
    (1820, "Gopinath", "Expense", "Gopinath", ""),
    (1821, "Hardwares & EE", "Expense", "3g mobile", "upi"),
    (1822, "Hardwares & EE", "Expense", "amba store", "upi"),
    (1823, "Hardwares & EE", "Expense", "electricals", "upi"),
    (1824, "HDFC Life", "Expense", "HDFC Life", ""),
    (1825, "HDFC Life", "Expense", "sbin2250080903300097160044302", ""),
    (1826, "Health Insurance", "Insurance", "arogya policy", "sbi general insurance"),
    (1827, "Hospital", "Expense", "g g hospital", "upi"),
    (1828, "Hospital", "Expense", "vasan health care", "upi"),
    (1829, "Hospital-M&D", "Expense", "precise", "upi"),
    (1830, "iCloud", "Transfer", "apple media", "wdl tfr"),
    (1831, "Int FD", "Income", "INT ON FD INR", ""),
    (1832, "Int Income", "Income", ":int.pd:", ""),
    (1833, "Int Income", "Income", "INTEREST CREDIT", ""),
    (1834, "Interest", "Income", "43438795987", "int trf"),
    (1835, "Interest", "Income", "int trf", "deposit transfer"),
    (1836, "Interest", "Income", "sbint", ""),
    (1837, "JIO", "Bill", "air fiber", ""),
    (1838, "JIO", "Bill", "JIO", ""),
    (1839, "KSEB", "Bill", "67343257007", ""),
    (1840, "KSEB", "BIll", "government of kerala bill", "payments"),
    (1841, "KSEB", "Bill", "kerala state electricity", ""),
    (1842, "KSEB", "BIll", "kerala state electricity", "wdl tfr"),
    (1843, "KSEB", "Bill", "kseb", ""),
    (1844, "KSEB", "Bill", "rafikseb1972@o", ""),
    (1845, "KSEB", "BIll", "wl.keralastateelectricit", "upi"),
    (1846, "KSRTC", "Bill", "kerala state road transport", ""),
    (1847, "KSSTM", "Bill", "ksstm", ""),
    (1848, "KWAT", "Bill", "kwat", ""),
    (1849, "LIC", "Transfer", "neft:lic", ""),
    (1850, "Loan Repay", "Expense", "baiju  suseelan", "0038139287676"),
    (1851, "Loan Repay", "Loan repay", "loan repay", ""),
    (1852, "Loan Repay", "Expense", "loan repayment", "wdl tfr"),
    (1853, "Loan Repay", "Expense", "payoff loan", ""),
    (1854, "Locker Rent", "Locker", "locker  rent", ""),
    (1855, "Locker Rent", "Locker", "locker charges", "wdl tfr"),
    (1856, "Locker Rent", "Locker", "locker rent", "wdl tfr"),
    (1857, "Locker Rent", "Locker", "wdl tfr  locker rent", ""),
    (1858, "Locker Rent Reverse", "Locker", "locker excess rent", ""),
    (1859, "LULU", "Shopping", "lulu", ""),
    (1860, "LULU", "Shopping", "lulu international", ""),
    (1861, "LULU", "Shopping", "lulutrivandrum", "upi"),
    (1862, "Lulu Parking", "Expense", "parking booth", "upi"),
    (1863, "Lulu Parking", "Expense", "parkingbooth", "upi"),
    (1864, "Margin free", "Shopping", "margin free", "upi"),
    (1865, "MF", "MF", "debit-cmp", "sbimf"),
    (1866, "MF", "Income", "ulip surrender", ""),
    (1867, "Microsoft", "Business", "microsoft", ""),
    (1868, "Mom & Dad", "Expense", "0067015271014", ""),
    (1869, "Mom & Dad", "Expense", "67015271014", ""),
    (1870, "Mom & Dad", "Expense", "ajith ghosh m s", ""),
    (1871, "Mom & Dad", "Expense", "mr. suseelan  kunjuram", ""),
    (1872, "Mom & Dad", "Expense", "suseelan  kunjuram", "0067015271014"),
    (1873, "Monthly Budget", "Expense", "monthly budget", ""),
    (1874, "MORE", "Expense", "more", ""),
    (1875, "MORE", "Expense", "more.61839497@", ""),
    (1876, "MORE", "Expense", "more.61839878@", ""),
    (1877, "MORE", "Expense", "moreretail", ""),
    (1878, "MORE", "Expense", "prasanth nagar trivandrum 31", ""),
    (1879, "MOT", "Expense", "mall of travancore", ""),
    (1880, "Netflix", "Expense", "Netflix", ""),
    (1881, "NPS", "Investment", "national pension scheme", "wdl tfr  inb"),
    (1882, "NPS", "Investment", "nps cams", "upi"),
    (1883, "Opening Balance", "Income", "opening balance", "opening balance"),
    (1884, "Personal Exp", "Expense", "mohanan  p", "upi"),
    (1885, "Personal Exp", "Expense", "mohanan p/upi", "upi"),
    (1886, "Personal Exp", "Expense", "mohanan.p.kkm", "upi"),
    (1887, "Pharmacy", "Expense", "janasevana kendram", "upi"),
    (1888, "Pharmacy", "Expense", "kottackal arya vaidyasala", "upi"),
    (1889, "Pharmacy", "Expense", "medicals", "upi"),
    (1890, "Pharmacy", "Expense", "pharmacy", "upi"),
    (1891, "Pharmacy", "Expense", "royal kallambalam clinic", "upi"),
    (1892, "Pharmacy", "Expense", "royalkallambalamclinic", "upi"),
    (1893, "Pharmacy", "Expense", "vasudeva vilasam", "upi"),
    (1894, "POS", "Shopping", "pos", ""),
    (1895, "POS", "Shopping", "pos atm purch", ""),
    (1896, "Pothy", "Shopping", "pothys", "upi"),
    (1897, "Premier", "Shopping", "premier office", "upi"),
    (1898, "PVR", "Expense", "inox", ""),
    (1899, "PVR", "Expense", "INOX", "upi"),
    (1900, "PVR", "Expense", "pvr inox", "upi"),
    (1901, "PVR", "Expense", "pvr limited", "wdl tfr"),
    (1902, "PVR", "Expense", "pvr limited", ""),
    (1903, "PVR", "Expense", "pvrcinemas", "upi"),
    (1904, "PVR", "Expense", "pvrcinemasoffline", "upi"),
    (1905, "PVR", "Expense", "pvrinox831352", ""),
    (1906, "PVR", "Expense", "pvrinoxlimited", ""),
    (1907, "PVR", "Expense", "pvrinoxlimited", "upi"),
    (1908, "Ramachandran", "Shopping", "ramachandran", "upi"),
    (1909, "Reliance", "Shopping", "Reliance", ""),
    (1910, "Restaurants", "Expense", "bakery", "upi"),
    (1911, "Restaurants", "Expense", "bhavan", "upi"),
    (1912, "Restaurants", "Expense", "biryani", "upi"),
    (1913, "Restaurants", "Expense", "cafe", "upi"),
    (1914, "Restaurants", "Expense", "cake world", "upi"),
    (1915, "Restaurants", "Expense", "chothys hospitality", "upi"),
    (1916, "Restaurants", "Expense", "foods", "upi"),
    (1917, "Restaurants", "Expense", "fruit juices", "upi"),
    (1918, "Restaurants", "Expense", "hi tea", "upi"),
    (1919, "Restaurants", "Expense", "hotel", "upi"),
    (1920, "Restaurants", "Expense", "master chef", "upi"),
    (1921, "Restaurants", "Expense", "mc donalds", "upi"),
    (1922, "Restaurants", "Expense", "Restaurant", "upi"),
    (1923, "Restaurants", "Expense", "taco bell", "upi"),
    (1924, "Restaurants", "Expense", "vegeatz", "upi"),
    (1925, "Reverse", "Income", "reverse", ""),
    (1926, "Reverse", "Income", "reversed", ""),
    (1927, "SALARY", "Income", "QPAY", ""),
    (1928, "SBI", "BANK", "SBI", ""),
    (1929, "SBI", "BANK", "State Bank of India", ""),
    (1930, "SBI->FED", "Transfer", "sbinr52023070559034557", ""),
    (1931, "SBI->SIB", "Transfer", "/baiju suseelan nair/moblta", ""),
    (1932, "SBI-Life", "Expense", "SBI-Life", ""),
    (1933, "SBI-NRE-4250", "Transfer", "transfer from 57013904250", ""),
    (1934, "SBI-NRO-9418", "Transfer", "67093359418", ""),
    (1935, "SBI-NRO-9418", "Transfer", "transfer to 67093359418", ""),
    (1936, "Self", "Expense", "9539056194@upi", "upi"),
    (1937, "Self", "Expense", "9539056194@upi", ""),
    (1938, "Self", "Transfer", "baiju suseelan", "wdl tfr"),
    (1939, "Self", "Transfer", "baiju suseelan nair", "upi"),
    (1940, "Self", "Transfer", "baiju suseelan nair/upi", "upi"),
    (1941, "Self", "Transfer", "baiju.s.nair-outlook.com", "upi"),
    (1942, "Self", "Transfer", "baijususeelannair", "upi/fdrl"),
    (1943, "Self", "Transfer", "baijususeelannair@upi", "upi"),
    (1944, "Self", "Transfer", "direct dr", "0067093359418"),
    (1945, "Self", "Transfer", "mr. baiju  suseelan", "0067093359418"),
    (1946, "Self", "Transfer", "mr. baiju  suseelan", "wdl tfr"),
    (1947, "Self", "Transfer", "own account", "mob"),
    (1948, "Self", "Expense", "sbin123186822129", "neft"),
    (1949, "Self", "EOSB", "sbin322249093092", ""),
    (1950, "ShareMarket", "Income", "BULK POSTING-ACHCr", ""),
    (1951, "ShareMarket", "Income", "BULK POSTING-SBIMF", ""),
    (1952, "ShareMarket", "Expense", "nach", ""),
    (1953, "ShareMarket", "Income", "nach_cr", ""),
    (1954, "ShareMarket", "Income", "SHARES AND BONDS", ""),
    (1955, "SIB", "BANK", "SIB", ""),
    (1956, "SIB", "BANK", "South Indian Bank", ""),
    (1957, "SIB<->SIB", "Transfer", "mob/friends/baiju suseelan nair/", ""),
    (1958, "SIB<->SIB", "Transfer", "mob/own account/baiju suseelan nair/", ""),
    (1959, "SIB-NRE-49", "Transfer", "049sibl", ""),
    (1960, "SIB-NRE-49", "Transfer", "049sibl", "wdl tfr"),
    (1961, "SIB-NRE-49", "Transfer to", "XX0049/Pay to acc", ""),
    (1962, "SIB-NRO-60", "Transfer", "060sibl", ""),
    (1963, "SIB-NRO-81", "Transfer", "/sibl-xx081", ""),
    (1964, "SIB-NRO-81", "Transfer", "081sibl", ""),
    (1965, "SIB-NRO-81", "Transfer", "sibl-xx081", "wdl tfr"),
    (1966, "SIB-NRO-81", "Transfer", "wdl tfr  inb imps", "x081sibl"),
    (1967, "Sudheer", "Expense", "sudheer", "upi"),
    (1968, "Sudheer", "Expense", "sudheer  sasidharan", ""),
    (1969, "Sujith S", "Transfer", "neft:mr  sundaresan  sujith", ""),
    (1970, "Sun Homes", "Transfer", "67053179635", "sbilt"),
    (1971, "SUN Medanta", "Expense", "sun home", ""),
    (1972, "SUN Medanta", "Expense", "sunmedanta", ""),
    (1973, "SUN Medanta", "Expense", "sunmedanta apartment ownersa", ""),
    (1974, "Sun Store", "Expense", "vinu vijayan", ""),
    (1975, "Sun Store", "Expense", "vinu vijayan/upi", ""),
    (1976, "Suspense", "Expense", "0042318524988", ""),
    (1977, "Suspense", "Expense", "0042318738037", ""),
    (1978, "Suspense", "Expense", "43438814720", ""),
    (1979, "Suspense", "Expense", "43438814720", ""),
    (1980, "Suspense", "Expense", "99506044303", ""),
    (1981, "Suspense", "Expense", "322199330305", ""),
    (1982, "Suspense", "Expense", "sbin123044482258", ""),
    (1983, "Suspense", "Expense", "sbin422256210622", ""),
    (1984, "Suspense Expense Account", "Expense", "98047706316", ""),
    (1985, "Suspense Expense Account", "Expense", "sbin3242273821520097162044301", ""),
    (1986, "Suspense Expense Account", "Expense", "sbin1242138970100097942044308", ""),
    (1987, "Swiggy", "Expense", "swiggy", ""),
    (1988, "Swiggy", "Expense", "swiggy1online", ""),
    (1989, "Swiggy", "Expense", "swiggyinstamar", ""),
    (1990, "Swiggy", "Expense", "swiggystores", ""),
    (1991, "Swiggy", "Expense", "swiggyupi", ""),
    (1992, "Swiggy", "Expense", "upiswiggy", ""),
    (1993, "TAX", "Tax", "kerala mission", ""),
    (1994, "TAX", "Tax", "9539056194@upi/Tax", ""),
    (1995, "TAX", "Tax", "Tax", ""),
    (1996, "TAX", "Tax", "Tax/UPI", ""),
    (1997, "Temple", "Donation", "9539056194@upi/Mukalvata", ""),
    (1998, "Temple", "Donation", "Mukalvat/UPI", ""),
    (1999, "Temple", "Temple", "SREE PANCHAMI DEVI TEMPLE", ""),
    (2000, "Temple", "Temple", "travancore devaswom board", ""),
    (2001, "To FD", "Expense", "0043438795987", ""),
    (2002, "To FD", "Expense", "0043438814720", ""),
    (2003, "To FD", "Transfer", "dr. tran for funding", ""),
    (2004, "Transportation", "Transportation", "irctc", "upi"),
    (2005, "UPI", "Income", "UPI IN", "UPI"),
    (2006, "UPI", "Income", "UPI IN/", "UPI"),
    (2007, "UPI", "UPI", "upi/", "UPI"),
    (2008, "UPI", "Expense", "UPI/airp", "UPI"),
    (2009, "UPI", "Transfer", "upi/fdrl", "UPI"),
    (2010, "UPI", "Expense", "UPIOUT", "UPI"),
    (2011, "UPI", "Income", "UPIREV", "UPI"),
    (2012, "USD Transfer", "Expense", "cash wdl usd", ""),
    (2013, "Vegetable", "Expense", "/shambukumar", "upi"),
    (2014, "Venus", "Transfer", "99506044303", "venus apprtment"),
    (2015, "Venus", "Transfer", "advvsvk@", "upi"),
    (2016, "Vineeth", "Transfer", "lawqua", "upi"),
    (2017, "Vineeth", "Transfer", "vineeth kumar", "wdl tfr  transfer"),
    (2018, "Vineeth", "Transfer", "vineeth kumar  v", "upi/sbin"),
    (2019, "Vineeth", "Transfer", "wdl tfr", "67006724124"),
    (2020, "Vodafone", "Expense", "vodafone", ""),
    (2021, "Wife", "Expense", "9446040282@upi", "upi"),
    (2022, "Wife", "Expense", "Sumee", "upi"),
    (2023, "Wife", "Expense", "sumee", "rtg/sumee s/fdrlr"),
    (2024, "Wife", "Expense", "sumee  s", "upi"),
    (2025, "Wife", "Income", "sumee  s/upi", "upi"),
    (2026, "XUV Insurance", "Expense", "Policy-Bazar", ""),
    (2027, "XUV Tyre", "Expense", "royal tyre club", ""),
    (2028, "Zomato", "Expense", "oidztdupic", ""),
    (2029, "Zomato", "Expense", "payzomato", ""),
    (2030, "Zomato", "Expense", "zomato", "UPI"),
    (2031, "Zomato", "Expense", "zomato1paytm", ""),
    (2032, "Zomato", "Expense", "zomatoonlineorder", ""),
    (2033, "Zomato", "Expense", "zomatoonlineorder.rzp", ""),
    (2034, "Zomato", "Expense", "zomato-order", "UPI"),
    # 🎯 UPDATED SEED ENTRIES (NO REAL NAMES RECORDED)
    (
        2035,
        "Charity",
        "Donation",
        "0511c6db4db5cd73b76173a13eb1f0b084475378cfc3842f96e1b5bbc3378de7",
        "",
    ),
    (
        2036,
        "Charity",
        "Donation",
        "3f5979368ea97fd1327d13cb80e423fc11cb457bd3fea5de247d74d08fc5e524",
        "",
    ),
    (
        2037,
        "Charity",
        "Donation",
        "b56acfa18a18fff006223c2a1d5b2183d40e71c2c835f52998643fc87b9a85bb",
        "",
    ),
    (1765, "Charity", "Donation", "42321673786", "wdl tfr"),
    (1766, "Charity", "Donation", "42321674532", "wdl tfr"),
    (1767, "Charity", "Donation", "42380688363", "wdl tfr"),
    (1768, "Charity", "Donation", "42380692084", "wdl tfr"),
    (1769, "Charity", "Donation", "67091477682", "wdl tfr"),
    (1770, "Charity", "Donation", "67374881869", "direct dr"),
    (2041, "Charity", "Donation", "67374881869", "direct"),
    # P1: 0511c6db4db5cd73b76173a13eb1f0b084475378cfc3842f96e1b5bbc3378de7
    # P2: 3f5979368ea97fd1327d13cb80e423fc11cb457bd3fea5de247d74d08fc5e524
    # P3: b56acfa18a18fff006223c2a1d5b2183d40e71c2c835f52998643fc87b9a85bb
    # this is a different name for the same charity donation, so we can use this to identify the same category
    # P1: aa99d87586749f3ad2b2e2ed1e07fddf6e569cd532aeb7f00158a6f52eae7f13
    # P2: 10b274a0ff32dded8515a2c779cca8b965c1b84a12bf4cbd2b7c00e8e12dc380
    # P3: 083aa324f7805d6e016717a0fd3c7d22ab91fa1e120a92bdcb80fdabaefaf246
    (2038, "Payouts", "Investment Cleared", "cemtex", ""),
    (2039, "Tax", "TAX", "kerala flood", "cess"),
    (2040, "Income", "Income", "clearing", "cheque"),
    (2042, "Investment", "Mutual Funds", "MF", "ECS COLLECTION"),
    (2043, "Expenses", "Insurance Premiums", "DEBIT", "INSURANCE"),
    (2044, "Investment", "Investment", "FOREX", "0111121TP054863"),
    (2045, "Investment", "Expense", "FCNB", "STAMP"),
    (2046, "Suspense", "Uncategorized", "0098324706317", ""),
    (2047, "Bank Charge", "Expense", "sms banking", "charges"),
    (2048, "Expenses", "Expense", "By Cash", "Cash"),
    (2049, "Liabilities", "Loans & Repayments", "loan", "payment"),
    (2050, "Interest", "Income", "int", "cr"),
    (2051, "Investment", "Shares", "Trading", ""),
    (2052, "Investment", "Shares", "Geojith", ""),
    (2053, "Investment", "Shares", "capstocks", ""),
    (2054, "Personal Exp", "Expense", "mohanan p", "upi"),
    (2055, "LAW", "Expense", "POWER", "att"),
    (2056, "Expenses", "Expense", "DTH", "rech"),
    (2057, "Temple", "Temple", "devaswom", "board"),
    (2058, "Temple", "Temple", "temple", "praveen"),
    (2059, "Expenses", "Expense", "AIRTEL", "BOX"),
    (2060, "Temple", "Pooja", "sunil shanti", ""),
    (2061, "Personal Exp", "Expense", "PRAVEEN", ""),
    (2062, "Investment", "Mutual Funds", "CLG", ""),
    (2063, "Expenses", "Vehicle Insurance", "Scropio", "Insurance"),
    (2064, "Expenses", "Vehicle", "Scropio", ""),
    (2065, "Expenses", "Employee", "Transfer", "Praveen"),
    (2066, "Expenses", "Employee", "Petty", "Praveen"),
    (2067, "Expenses", "Employee", "Advance", "Praveen"),
    (2068, "Expenses", "Office", "Window", "Inst"),
    (2069, "SUN Medanta", "Expense", "sun medanta", ""),
    (2070, "SUN Medanta", "Expense", "reement", "fund"),
    (2071, "Expenses", "Office", "meter", "Praveen"),
    (2072, "Expenses", "Loan", "BDS", ""),
    (2073, "Expenses", "Loan", "bluedot", ""),
    (
        2074,
        "Charity",
        "Donation",
        "aa99d87586749f3ad2b2e2ed1e07fddf6e569cd532aeb7f00158a6f52eae7f13",
        "",
    ),
    (
        2075,
        "Charity",
        "Donation",
        "10b274a0ff32dded8515a2c779cca8b965c1b84a12bf4cbd2b7c00e8e12dc380",
        "",
    ),
    (
        2076,
        "Charity",
        "Donation",
        "083aa324f7805d6e016717a0fd3c7d22ab91fa1e120a92bdcb80fdabaefaf246",
        "",
    ),
    (
        2077,
        "Charity",
        "Donation",
        "083aa324f7805d6e016717a0fd3c7d22ab91fa1e120a92bdcb80fdabaefaf246",
        "",
    ),
    (2078, "Investment", "Shares", "Geojit", ""),
    (2079, "Interest", "Income", "int", ""),
    (2080, "Expenses", "Expense", "self", "exp"),
    (2081, "SUN Medanta", "Expense", "REMNT", "fund"),
    (2082, "SUN Medanta", "Expense", "REMNT", "fund"),
    (2083, "Investment", "Shares", "COCHIN SHIPYARD", ""),
    (2084, "Bank Charge", "Fees", "DEBit", "charges"),
    (2085, "Bank Charge", "Fees", "charges", ""),
    (2086, "Self Transfer", "Transfer", "Friends", "Baiju"),
    (2085, "Bank Charge", "Fees", "charge", ""),
    # for UPI's
    # 🎯 STARTING FROM SNO 2086 (KEY1 COMPILATION, NO KEY2 KEYS SET)
    (2086, "Arun", "Expense", "baratkgopinath1998", ""),
    (2087, "Arun", "Expense", "barat k gopinath", ""),
    (2088, "Vineeth", "Transfer", "vineeth kumar  v ", ""),
    (2089, "Vineeth", "Transfer", "advvsvk@", ""),
    (2090, "Vineeth", "Transfer", "lawqua", ""),
    (2091, "Wife", "Expense", "sumee  s", ""),
    (2092, "Wife", "Expense", "sumee", ""),
    (2093, "Wife", "Income", "sumee  s/upi", ""),
    (2094, "Wife", "Expense", "rtg/sumee s/fdrlr", ""),
    (2095, "Wife", "Expense", "9446040282@upi", ""),
    (2096, "Transportation", "Expense", "autotransport", ""),
    (2097, "Amazon", "Shopping", "amazon", ""),
    (2098, "Amazon", "Shopping", "amazon india", ""),
    (2099, "Amazon", "Shopping", "amazon seller", ""),
    (2100, "Amazon", "Shopping", "amazonupi", ""),
    (2101, "PVR", "Expense", " pvr limited", ""),
    (2102, "XUV Insurance", "Expense", "policy-bazar", ""),
    (2103, "XUV Tyre", "Expense", "royal tyre club", ""),
    (2104, "Zomato", "Expense", "zomatoonlineorder", ""),
    (2105, "Zomato", "Expense", "zomato-order", ""),
    (2106, "Zomato", "Expense", "zomato1paytm", ""),
    (2107, "Zomato", "Expense", "payzomato", ""),
    (2108, "Zomato", "Expense", "oidztdupic", ""),
    (2109, "Zomato", "Expense", "zomato", ""),
    (2110, "Zomato", "Expense", "zomatoonlineorder.rzp", ""),
    (2111, "Fish", "Expense", "padhayam fish mart", ""),
    (2112, "Pharmacy", "Expense", "janashraya community pharmac", ""),
    (2113, "Beena", "Expense", "ms. beena thingal", ""),
    (2114, "Beena", "Expense", "beena thingal", ""),
    (2115, "Disney Hotstar", "Bill", "disney hotsta", ""),
    (2116, "FUEL", "Fuel", "fuels", ""),
    (2117, "Fuel", "Expense", "nagarajan and sons", ""),
    (2118, "Fuel", "Expense", "nagarajan s", ""),
    (2119, "GAS", "Expense", "gas", ""),
    (2120, "GODADDY", "Expense", "godaddy", ""),
    (2121, "Google", "Business", "google", ""),
    (2122, "Gopinath", "Expense", "gkinter2000-1@", ""),
    (2123, "Gopinath", "Expense", "gopinath", ""),
    (2124, "City Plaza (Expense)", "Expense", "city plaza", ""),
    (2125, "City Plaza (Maintenance)", "Expense", "city plaza flat owners  asso", ""),
    (2126, "City Plaza (Rent)", "Transfer", "neenu  joseph", ""),
    (2127, "Sudheer", "Expense", "sudheer  sasidharan", ""),
    (2128, "Sujith S", "Transfer", "neft:mr  sundaresan  sujith", ""),
    (2129, "SUN Medanta", "Expense", "sun home", ""),
    (2130, "SUN Medanta", "Expense", "sunmedanta apartment ownersa", ""),
    (2131, "SUN Medanta", "Expense", "sunmedanta", ""),
    (2132, "Sun Store", "Expense", "vinu vijayan/upi", ""),
    (2133, "Sun Store", "Expense", "vinu vijayan", ""),
    (2134, "Swiggy", "Expense", "swiggyupi", ""),
    (2135, "Swiggy", "Expense", "swiggy", ""),
    (2136, "Swiggy", "Expense", "upiswiggy", ""),
    (2137, "Swiggy", "Expense", "swiggystores", ""),
    (2138, "Swiggy", "Expense", "swiggy1online", ""),
    (2139, "Swiggy", "Expense", "swiggyinstamar", ""),
    (2140, "TAX", "Tax", "9539056194@upi/tax", ""),
    (2141, "TAX", "Tax", "tax/upi", ""),
    (2142, "TAX", "Tax", " kerala mission", ""),
    (2143, "TAX", "Tax", "tax", ""),
    (2144, "Temple", "Donation", "9539056194@upi/mukalvata", ""),
    (2145, "Temple", "Donation", "mukalvat/upi", ""),
    (2146, "Temple", "Temple", "travancore devaswom board", ""),
    (2147, "Temple", "Temple", "sree panchami devi temple", ""),
    (2148, "Monthly Budget", "Expense", "monthly budget", ""),
    (2149, "MORE", "Expense", "more.61839497@", ""),
    (2150, "MORE", "Expense", "more.61839878@", ""),
    (2151, "MORE", "Expense", "moreretail", ""),
    (2152, "MORE", "Expense", "more", ""),
    (2153, "MORE", "Bill", "prasanth nagar trivandrum 31", ""),
    (2154, "MOT", "Expense", "mall of travancore", ""),
    (2155, "Netflix", "Expense", "netflix", ""),
    (2156, "JIO", "Bill", "air fiber", ""),
    (2157, "JIO", "Bill", "jio", ""),
    (2158, "KSEB", "Bill", "67343257007", ""),
    (2159, "KSEB", "Bill", "kerala state electricity", ""),
    (2160, "KSEB", "Bill", "kseb", ""),
    (2161, "KSEB", "Bill", "rafikseb1972@o", ""),
    (2162, "KSRTC", "Bill", "kerala state road transport", ""),
    (2163, "KSSTM", "Bill", "ksstm", ""),
    (2164, "KWAT", "Bill", "kwat", ""),
    ####
    (2165, "Expenses", "Expense", "9539056194", "UPI"),
    (2166, "Personal Exp", "Expense", "ATM", "self"),
]

# ==============================================================================
# 🔄 DATA DEPOSIT SET 3: INTER-BANK TRANSFER MATRICES (SELF_TRANSFER)
# ==============================================================================
SELFTRANSFER_SOURCE_ROWS = [
    (
        369,
        "SBI-NRE-4250",
        "SBI-NRO-9418",
        "67093359418",
        "",
        "By SBI-NRE-4250 To SBI-NRO-9418",
        "Self",
    ),
    (
        370,
        "SBI-NRE-4250",
        "SBI-NRO-9418",
        "tfrtransfer",
        "0041470556908",
        "By SBI-NRE-4250 To SBI-NRO-9418",
        "Self",
    ),
    (
        371,
        "SBI-NRE-4250",
        "SBI-NRO-9418",
        "tfrtransfer",
        "0038139287676",
        "By SBI-NRE-4250 To SBI-NRO-9418",
        "Self",
    ),
    (372, "SBI-NRE-4250", "Saudi", "qpay", "", "By Saudi To SBI-NRE-4250", ""),
    (
        373,
        "SBI-NRE-4250",
        "FED-NRE-2763",
        "x763",
        "",
        "By SBI-NRE-4250 To FED-NRE-2763",
        "Self",
    ),
    (
        374,
        "SBI-NRE-4250",
        "FED-NRO-1050",
        "x050",
        "",
        "By SBI-NRE-4250 To FED-NRO-1050",
        "Self",
    ),
    (
        375,
        "SBI-NRE-4250",
        "SIB-NRE-49",
        "x049",
        "",
        "By SBI-NRE-4250 To SIB-NRE-49",
        "Self",
    ),
    (
        376,
        "SBI-NRE-4250",
        "SIB-NRE-49",
        "x0049",
        "",
        "By SIB-NRE-49 To SBI-NRE-4250",
        "Self",
    ),
    (
        377,
        "SBI-NRE-4250",
        "SIB-NRO-60",
        "x060",
        "",
        "By SBI-NRE-4250 To SIB-NRO-60",
        "Self",
    ),
    (
        378,
        "SBI-NRE-4250",
        "SIB-NRO-81",
        "x081",
        "",
        "By SBI-NRE-4250 To SIB-NRO-81",
        "Self",
    ),
    (
        379,
        "SBI-NRE-4250",
        "FED-NRE-2763",
        "sbin124288798470",
        "",
        "By SBI-NRE-4250 To FED-NRE-2763",
        "Self",
    ),
    (
        380,
        "SBI-NRE-4250",
        "FED-NRE-2763",
        "sbin123186822129",
        "",
        "By SBI-NRE-4250 To FED-NRE-2763",
        "Self",
    ),
    (
        381,
        "SBI-NRE-FD",
        "SBI-NRE-4250",
        "0043438795987",
        "",
        "By SBI-NRE-FD To SBI-NRE-4250",
        "FD",
    ),
    (
        382,
        "SBI-NRE-4250",
        "SBI-NRE-FD",
        "0043438814720",
        "",
        "By SBI-NRE-4250 To SBI-NRE-FD",
        "Self",
    ),
    (
        383,
        "SBI-NRO-9418",
        "FED-NRE-1050",
        "x050",
        "",
        "By SBI-NRO-9418 To FED-NRE-1050",
        "Self",
    ),
    (
        384,
        "SBI-NRO-9418",
        "SIB-NRO-60",
        "x060",
        "",
        "By SBI-NRO-9418 To SIB-NRO-60",
        "Self",
    ),
    (
        385,
        "SBI-NRO-9418",
        "SBI-NRE-4250",
        "57013904250",
        "",
        "By SBI-NRE-4250 To SBI-NRO-9418",
        "Self",
    ),
    (
        386,
        "SBI-NRO-9418",
        "SIB-NRO-81",
        "xxx081",
        "",
        "By SBI-NRO-9418 To SIB-NRO-81",
        "Self",
    ),
    (
        387,
        "SBI-NRO-9418",
        "SBI-NRE-4250",
        "tfrtransfer",
        "0041470556908",
        "By SBI-NRE-4250 To SBI-NRO-9418",
        "Self",
    ),
    (
        388,
        "SBI-NRO-9418",
        "SBI-NRE-4250",
        "tfrtransfer",
        "0038139287676",
        "By SBI-NRE-4250 To SBI-NRO-9418",
        "Self",
    ),
    (
        389,
        "SBI-NRO-9418",
        "Suspense",
        "0042318738037",
        "",
        "By SBI-NRO-9418 To SBI-NRO-9418",
        "Self",
    ),
    (
        390,
        "SBI-NRO-9418",
        "Suspense",
        "0042318524988",
        "",
        "By SBI-NRO-9418 To SBI-NRO-9418",
        "Self",
    ),
    (
        391,
        "SBI-NRO-9418",
        "Suspense",
        "99506044303",
        "",
        "By SBI-NRO-9418 To Suspense",
        "",
    ),
    (
        392,
        "SBI-NRO-9418",
        "SIB-NRO-81",
        "/428910751459",
        "",
        "By SIB-NRO-81 To SBI-NRO-9418",
        "Self",
    ),
    (
        393,
        "SBI-NRO-9418",
        "SIB-NRO-81",
        "2.32215E+11",
        "imps/ifsc/",
        "By SBI-NRO-9418 To SIB-NRO-81",
        "Self",
    ),
    (
        394,
        "SBI-NRO-9418",
        "Suspense",
        "452209",
        "from 67000635783",
        "By SBI-NRO-9418 To Suspense",
        "",
    ),
    (
        395,
        "FED-NRE-2763",
        "SBI-NRE-4250",
        "sbin123186822129",
        "",
        "By SBI-NRE-4250 To FED-NRE-2763",
        "Self",
    ),
    (
        396,
        "FED-NRE-2763",
        "EOSB",
        "sbin322249093092",
        "",
        "By EOSB To FED-NRE-2763",
        "",
    ),
    (
        397,
        "FED-NRE-2763",
        "SBI-NRE-4250",
        "57013904250",
        "",
        "By SBI-NRE-4250 To FED-NRE-2763",
        "Self",
    ),
    (
        398,
        "FED-NRE-2763",
        "SBI-NRE-4250",
        "sbin124288798470",
        "",
        "By SBI-NRE-4250 To FED-NRE-2763",
        "Self",
    ),
    (
        399,
        "FED-NRE-2763",
        "SBI-NRO-9418",
        "67093359418",
        "",
        "By FED-NRE-2763 To SBI-NRO-9418",
        "Self",
    ),
    (
        400,
        "FED-NRE-2763",
        "SBI-NRO-9418",
        "fdrlr52023102100362197",
        "",
        "By FED-NRE-2763 To SBI-NRO-9418",
        "Self",
    ),
    (401, "FED-NRE-2763", "Saudi", "qpay", "", "By Saudi To FED-NRE-2763", ""),
    (
        402,
        "FED-NRE-2763",
        "FED-NRO-1050",
        "x050",
        "",
        "By FED-NRE-2763 To FED-NRO-1050",
        "Self",
    ),
    (
        403,
        "FED-NRE-2763",
        "FED-NRO-1050",
        "mb fto",
        "",
        "By FED-NRE-2763 To FED-NRO-1050",
        "Self",
    ),
    (
        404,
        "FED-NRE-2763",
        "FED-NRO-1050",
        "mb ftb",
        "baiju suseelannair",
        "By FED-NRE-2763 To FED-NRO-1050",
        "Self",
    ),
    (
        405,
        "FED-NRE-2763",
        "FED-NRO-1050",
        "sbonr-21784100001050",
        "",
        "By FED-NRO-1050 To FED-NRE-2763",
        "Self",
    ),
    (
        406,
        "FED-NRE-2763",
        "FED-NRO-1050",
        "tfr:sbonr",
        "",
        "By FED-NRE-2763 To FED-NRO-1050",
        "Self",
    ),
    (
        407,
        "FED-NRE-2763",
        "SIB-NRE-49",
        "x049",
        "",
        "By FED-NRE-2763 To SIB-NRE-49",
        "Self",
    ),
    (
        408,
        "FED-NRE-2763",
        "Suspense",
        "sbin222249981497",
        "",
        "By Suspense To FED-NRE-2763",
        "",
    ),
    (
        409,
        "FED-NRO-1050",
        "SIB-NRO-60",
        "upiout",
        "baiju.s.nair-outlook.com",
        "By FED-NRO-1050 To SIB-NRO-60",
        "Self",
    ),
    (
        410,
        "FED-NRE-2763",
        "SIB-NRO-60",
        "x060",
        "",
        "By FED-NRE-2763 To SIB-NRO-60",
        "Self",
    ),
    (
        411,
        "FED-NRE-2763",
        "SIB-NRO-81",
        "x081",
        "",
        "By FED-NRE-2763 To SIB-NRO-81",
        "Self",
    ),
    (
        412,
        "FED-NRE-2763",
        "SBI-NRE-4250",
        "nft/baiju suseelan",
        "sbi",
        "By FED-NRE-2763 To SIB-NRE-4250",
        "Self",
    ),
    (
        413,
        "FED-NRE-2763",
        "SBI-NRE-4250",
        "mps/ifo",
        "SBIN",
        "By SBI-NRE-4250 To FED-NRE-2763",
        "Self",
    ),
    (
        414,
        "FED-NRO-1050",
        "SBI-NRO-9418",
        "67093359418",
        "",
        "By FED-NRO-1050 To SBI-NRO-9418",
        "Self",
    ),
    (
        415,
        "FED-NRO-1050",
        "SBI-NRO-9418",
        "fdrlr52023102100362120",
        "",
        "By FED-NRO-1050 To SBI-NRO-9418",
        "Self",
    ),
    (
        416,
        "FED-NRO-1050",
        "SBI-NRO-9418",
        "fdrlr52023100300751836",
        "",
        "By FED-NRO-1050 To SBI-NRO-9418",
        "Self",
    ),
    (
        417,
        "FED-NRO-1050",
        "FED-NRE-2763",
        "mb fto",
        "baiju suse",
        "By FED-NRE-2763 To FED-NRO-1050",
        "Self",
    ),
    (
        418,
        "FED-NRO-1050",
        "SIB-NRO-60",
        "x060",
        "",
        "By FED-NRO-1050 To SIB-NRO-60",
        "Self",
    ),
    (
        419,
        "FED-NRO-1050",
        "SIB-NRO-81",
        "x081",
        "",
        "By FED-NRO-1050 To SIB-NRO-81",
        "Self",
    ),
    (
        420,
        "FED-NRO-1050",
        "SIB-NRO-60",
        "upi in",
        "9539056194@upi",
        "By SIB-NRO-60 To FED-NRO-1050",
        "Self",
    ),
    (
        421,
        "FED-NRO-1050",
        "SIB-NRO-60",
        "upi out",
        "9539056194@upi",
        "By FED-NRO-1050 To SIB-NRO-60",
        "Self",
    ),
    (
        422,
        "FED-NRO-1050",
        "SIB-NRO-60",
        "upiout",
        "baijususeelannair@upi",
        "By FED-NRO-1050 To SIB-NRO-60",
        "Self",
    ),
    (
        423,
        "FED-NRO-1050",
        "SIB-NRO-60",
        "upi out",
        "baijususeelannair@upi",
        "By FED-NRO-1050 To SIB-NRO-60",
        "Self",
    ),
    (
        424,
        "FED-NRO-1050",
        "SIB-NRO-60",
        "upiout",
        "9539056194@upi",
        "By FED-NRO-1050 To SIB-NRO-60",
        "Self",
    ),
    (425, "SIB-NRE-49", "Saudi", "qpay", "", "By Saudi To SIB-NRE-49", ""),
    (
        426,
        "SIB-NRE-49",
        "SBI-NRE-4250",
        "57013904250",
        "",
        "By SIB-NRE-49 To SBI-NRE-4250",
        "Self",
    ),
    (
        427,
        "SIB-NRE-49",
        "SBI-NRO-9418",
        "67093359418",
        "",
        "By SIB-NRE-49 To SBI-NRO-9418",
        "Self",
    ),
    (
        428,
        "SIB-NRE-49",
        "FED-NRE-2763",
        "x763",
        "",
        "By SIB-NRE-49 To FED-NRE-2763",
        "Self",
    ),
    (
        429,
        "SIB-NRE-49",
        "FED-NRO-1050",
        "x050",
        "",
        "By SIB-NRE-49 To FED-NRO-1050",
        "Self",
    ),
    (
        430,
        "SIB-NRE-49",
        "SIB-NRO-60",
        "x060",
        "",
        "By SIB-NRE-49 To SIB-NRO-60",
        "Self",
    ),
    (
        431,
        "SIB-NRE-49",
        "Suspense",
        "mob/own account/baiju suseelan nair/",
        "",
        "By SIB-NRE-49 To Suspense",
        "",
    ),
    (
        432,
        "SIB-NRE-49",
        "Suspense",
        "Own Account/IMPS/",
        "",
        "By Suspense To SIB-NRE-49",
        "",
    ),
    (
        433,
        "SIB-NRE-49",
        "Suspense",
        "rtgs: baiju suseelan nair/",
        "",
        "By Suspense To SIB-NRE-49",
        "",
    ),
    (
        434,
        "SIB-NRE-49",
        "Suspense",
        "neft:baiju suseelan nair/",
        "",
        "By Suspense To SIB-NRE-49",
        "",
    ),
    (
        435,
        "SIB-NRE-49",
        "SIB-NRO-81",
        "x081",
        "",
        "By SIB-NRE-49 To SIB-NRO-81",
        "Self",
    ),
    (
        436,
        "SIB-NRE-49",
        "Suspense",
        "neft:mr. baiju suseelan nair/",
        "",
        "By Suspense To SIB-NRE-49",
        "",
    ),
    (
        437,
        "SIB-NRO-60",
        "SBI-NRO-9418",
        "67093359418",
        "",
        "By SIB-NRO-60 To SBI-NRO-9418",
        "Self",
    ),
    (
        438,
        "SIB-NRO-60",
        "FED-NRO-1050",
        "x050",
        "",
        "By SIB-NRO-60 To FED-NRO-1050",
        "Self",
    ),
    (
        439,
        "SIB-NRO-60",
        "SIB-NRO-81",
        "x081",
        "",
        "By SIB-NRO-60 To SIB-NRO-81",
        "Self",
    ),
    (
        440,
        "SIB-NRO-60",
        "SIB-NRO-81",
        "baiju.s.nair-o",
        "baiju suseelan nair/upi/",
        "By SIB-NRO-60 To SIB-NRO-81",
        "Self",
    ),
    (
        441,
        "SIB-NRO-60",
        "Suspense",
        "mob/own account/baiju suseelan nair/",
        "",
        "By Suspense To SIB-NRO-60",
        "",
    ),
    (
        442,
        "SIB-NRO-60",
        "Suspense",
        "Own Account/IMPS",
        "",
        "By SIB-NRO-60 To Suspense",
        "",
    ),
    (
        443,
        "SIB-NRO-60",
        "FED-NRO-1050",
        "upi/fdrl",
        "9539056194@upi",
        "By FED-NRO-1050 To SIB-NRO-60",
        "Self",
    ),
    (
        444,
        "SIB-NRO-60",
        "FED-NRO-1050",
        "upi/fdrl",
        "/baijususeelann",
        "By FED-NRO-1050 To SIB-NRO-60",
        "Self",
    ),
    (
        445,
        "SIB-NRO-60",
        "SIB-NRO-81",
        "4.36517E+11",
        "upi/sibl/",
        "By SIB-NRO-60 To SIB-NRO-81",
        "Self",
    ),
    (
        446,
        "SIB-NRO-81",
        "SIB-NRO-60",
        "4.36517E+11",
        "upi/sibl/",
        "By SIB-NRO-60 To SIB-NRO-81",
        "Self",
    ),
    (
        447,
        "SIB-NRO-81",
        "FED-NRO-1050",
        "x050",
        "",
        "By SIB-NRO-81 To FED-NRO-1050",
        "Self",
    ),
    (
        448,
        "SIB-NRO-81",
        "FED-NRO-1050",
        "upi/fdrl/",
        "baijususeelann",
        "By SIB-NRO-81 To FED-NRO-1050",
        "Self",
    ),
    (
        449,
        "SIB-NRO-81",
        "FED-NRO-1050",
        "160623914471",
        "baiju suseelan nair",
        "By FED-NRO-1050 To SIB-NRO-81",
        "Self",
    ),
    (
        450,
        "SIB-NRO-81",
        "SIB-NRO-60",
        "x060",
        "",
        "By SIB-NRO-81 To SIB-NRO-60",
        "Self",
    ),
    (
        451,
        "SIB-NRO-81",
        "Suspense",
        "mob/own account/baiju suseelan nair/",
        "",
        "By Suspense To SIB-NRO-81",
        "",
    ),
    (
        452,
        "SBI-NRO-9418",
        "SIB-NRO-81",
        "sibl-xx081-",
        "",
        "By SIB-NRO-81 To SBI-NRO-9418",
        "Self",
    ),
    (
        453,
        "SBI-NRO-9418",
        "SIB-NRO-81",
        "322819270822",
        "",
        "By SIB-NRO-81 To SBI-NRO-9418",
        "Self",
    ),
    (
        454,
        "SIB-NRO-81",
        "SIB-NRO-60",
        "baiju.s.nair-o",
        "baiju suseelan nair/upi/",
        "By SIB-NRO-60 To SIB-NRO-81",
        "Self",
    ),
    (
        455,
        "SIB-NRO-81",
        "SBI-NRO-9418",
        "322819270822",
        "",
        "By SIB-NRO-81 To SBI-NRO-9418",
        "Self",
    ),
    (
        456,
        "SIB-NRO-81",
        "SBI-NRO-9418",
        "#xx9418",
        "",
        "By SIB-NRO-81 To SBI-NRO-9418",
        "Self",
    ),
    (
        457,
        "SIB-NRO-81",
        "SBI-NRO-9418",
        "/428910751459/own account/imps/",
        "",
        "By SIB-NRO-81 To SBI-NRO-9418",
        "Self",
    ),
    (
        458,
        "SIB-NRO-81",
        "SBI-NRO-9418",
        "imps/sbin",
        "/baiju suseelan nair",
        "By SBI-NRO-9418 To SIB-NRO-81",
        "Self",
    ),
    (
        459,
        "SIB-NRO-81",
        "SBI-NRO-9418",
        "2.32215E+11",
        "imps/ifsc",
        "By SBI-NRO-9418 To SIB-NRO-81",
        "Self",
    ),
    (
        460,
        "SIB-NRO-81",
        "Suspense",
        "neft:baiju suseelan nair/",
        "",
        "By Suspense To SIB-NRO-81",
        "",
    ),
    (
        461,
        "SBI-NRE-4250",
        "SBI-OD",
        "0038139287676",
        "",
        "By SBI-NRE-4250 To SBI-OD",
        "Self",
    ),
    (
        462,
        "UNKNOWN_ACC",
        "SBI-NRE-ATTINGAL",
        "0067133374886",
        "direct",
        "Direct Transfer via Attingal NRI Branch",
        "Self",
    ),
    (
        463,
        "SBT-NRE",
        "SBI-NRE-ATTINGAL",
        "52016120500000968",
        "SBT",
        "STATE BANK OF TRAVANCORE",
        "Self",
    ),
]


def seed_categories_matrix():
    print(
        "⏳ Executing final database seed runtime. Packing nested tokens into clean JSON blocks..."
    )

    with transaction.atomic():
        MasterFinancialCategory.objects.all().delete()

        # ─── PART A: PROCESS BALANCE SHEET REGISTRY (REGULAR) ───
        bs_count = 0
        for row in BALANCESHEET_SOURCE_ROWS:
            MasterFinancialCategory.objects.create(
                category_type="REGULAR",
                sno=row[0],
                act_category=row[1],
                act_subcategory=row[2],
                categories_items=row[3],
                dashboard_cat=row[4],
                remarks="Master Core Layout Target",
                monthly_expense=row[6],
                keys={},
                bank_types={},
            )
            bs_count += 1
        print(f"✅ Loaded {bs_count} layout records under 'REGULAR'.")

        # ─── PART B: PROCESS STRING TOKEN LOOKUPS (KNOWN_DEFAULT) ───
        kd_count = 0
        for row in KNOWNDEFAULT_SOURCE_ROWS:
            # 🎯 FIX: Realignment of positional indices
            act_cat = row[1]
            sub_cat = row[2]

            # Extract text keys cleanly
            raw_k1 = row[3]
            raw_k2 = row[4]

            # Normalize values & convert empty strings into clean JSON null/None values
            k1 = raw_k1.strip().lower() if (raw_k1 and raw_k1.strip()) else None
            k2 = raw_k2.strip().lower() if (raw_k2 and raw_k2.strip()) else None

            HASH_MAP = {
                "0511c6db4db5cd73b76173a13eb1f0b084475378cfc3842f96e1b5bbc3378de7": "BENEFICIARY_01",
                "3f5979368ea97fd1327d13cb80e423fc11cb457bd3fea5de247d74d08fc5e524": "BENEFICIARY_02",
                "b56acfa18a18fff006223c2a1d5b2183d40e71c2c835f52998643fc87b9a85bb": "BENEFICIARY_03",
                "aa99d87586749f3ad2b2e2ed1e07fddf6e569cd532aeb7f00158a6f52eae7f13": "BENEFICIARY_04",
                "10b274a0ff32dded8515a2c779cca8b965c1b84a12bf4cbd2b7c00e8e12dc380": "BENEFICIARY_04",
                "083aa324f7805d6e016717a0fd3c7d22ab91fa1e120a92bdcb80fdabaefaf246": "BENEFICIARY_04",
                "083aa324f7805d6e016717a0fd3c7d22ab91fa1e120a92bdcb80fdabaefaf246": "BENEFICIARY_04",
            }

            categories_items = HASH_MAP.get(k1, act_cat)

            MasterFinancialCategory.objects.create(
                category_type="KNOWN_DEFAULT",
                sno=row[0],
                act_category=act_cat,
                act_subcategory=sub_cat,
                categories_items=categories_items,
                dashboard_cat="Auto Routed",
                keys={"key1": k1, "key2": k2},  # 🎯 Properly packed JSON payload
                bank_types={},
                remarks="Automated text parsing lookup entry",
            )
            kd_count += 1
        print(
            f"✅ Loaded {kd_count} description text token lookups under 'KNOWN_DEFAULT'."
        )

        # ─── PART C: PROCESS INTER-BANK ROUTING NODES (SELF_TRANSFER) ───
        st_count = 0
        for row in SELFTRANSFER_SOURCE_ROWS:
            # Extract string tokens safely
            raw_k1 = row[3]
            raw_k2 = row[4]
            raw_self = row[6]

            # Convert empty strings ("") or blank spaces into proper database NULL/None values
            k1 = raw_k1.strip().lower() if (raw_k1 and raw_k1.strip()) else None
            k2 = raw_k2.strip().lower() if (raw_k2 and raw_k2.strip()) else None
            self_val = raw_self.strip() if (raw_self and raw_self.strip()) else None

            MasterFinancialCategory.objects.create(
                category_type="SELF_TRANSFER",
                sno=row[0],
                act_category="Assets",
                act_subcategory="Self Inter-Account Transfer",
                categories_items=row[5],
                dashboard_cat="Transfers",
                keys={
                    "key1": k1,
                    "key2": k2,
                },  # 🎯 Clean structural JSON object payload
                bank_types={
                    "from_bank": row[1].strip() if row[1] else None,
                    "to_bank": row[2].strip() if row[2] else None,
                },  # 🎯 Packed JSON metadata
                self_account=self_val,
                remarks="Inter-bank fund movement rule route",
            )
            st_count += 1
        print(
            f"✅ Loaded {st_count} inter-bank move matrix routers under 'SELF_TRANSFER'."
        )

    print("\n🎉 Category taxonomy tables successfully written with zero index clashes!")


if __name__ == "__main__":
    seed_categories_matrix()
