# Generated by Django 6.0.5 on 2026-06-04 17:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementStagingLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('raw_statement_date', models.DateField()),
                ('narration', models.TextField()),
                ('cheque_ref_number', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('running_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('routing_status', models.CharField(default='PENDING', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staging_lines', to='ledger.account')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staging_lines', to='ledger.bank')),
                ('suggested_contra_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staging_suggestions', to='ledger.account')),
            ],
            options={
                'verbose_name': 'Statement Staging Line',
                'verbose_name_plural': 'Statement Staging Lines',
                'ordering': ['raw_statement_date', 'uploaded_at'],
            },
        ),
    ]
