# Generated by Django 6.0.5 on 2026-06-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_statementstagingline'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementstagingline',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='statementstagingline',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='statementstagingline',
            name='row_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
