# Generated by Django 6.0.5 on 2026-06-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_statementstagingline_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankcredential',
            name='statement_password',
        ),
        migrations.AddField(
            model_name='bankcredential',
            name='password_vault',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
