# Generated by Django 6.0.5 on 2026-06-06 12:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_remove_bankcredential_statement_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementIngestRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(help_text='PDF, CSV, etc.', max_length=10)),
                ('vault_decrypted', models.BooleanField(default=False)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_debit_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_credit_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_row_count', models.IntegerField(default=0)),
                ('debit_line_count', models.IntegerField(default=0)),
                ('credit_line_count', models.IntegerField(default=0)),
                ('skipped_duplicate_count', models.IntegerField(default=0)),
                ('ingested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_channel', models.CharField(default='WEB_DASHBOARD', max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_logs', to='ledger.account')),
            ],
            options={
                'db_table': 'tracker_statement_ingest_registry',
                'ordering': ['-ingested_at'],
            },
        ),
    ]
