# Generated by Django 6.0.5 on 2026-06-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_statementingestregistry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statementingestregistry',
            options={},
        ),
        migrations.AlterModelTable(
            name='statementstagingline',
            table='ledger_statementstagingline',
        ),
    ]
