# Generated by Django 6.0.5 on 2026-06-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_alter_statementingestregistry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementingestregistry',
            name='report_from_date',
            field=models.DateField(blank=True, help_text='The explicit start date covered by the bank statement.', null=True),
        ),
        migrations.AddField(
            model_name='statementingestregistry',
            name='report_to_date',
            field=models.DateField(blank=True, help_text='The explicit end date covered by the bank statement.', null=True),
        ),
    ]
