# Generated by Django 6.0.5 on 2026-06-07 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_statementingestregistry_report_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementstagingline',
            name='ingest_registry',
            field=models.ForeignKey(blank=True, help_text='The parent file upload profile history record linked to this transaction.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staging_lines', to='ledger.statementingestregistry'),
        ),
    ]
