# Generated by Django 6.0.5 on 2026-06-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_statementstagingline_ingest_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementstagingline',
            name='bank_transaction_id',
            field=models.CharField(blank=True, help_text='Core banking transaction system identifier string (e.g., S29270471, FB209745)', max_length=100, null=True),
        ),
    ]
