# Generated by Django 6.0.5 on 2026-06-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_statementstagingline_bank_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementstagingline',
            name='transaction_type',
            field=models.CharField(blank=True, help_text='e.g., NFT, UPI, CHQ, TFR', max_length=50, null=True),
        ),
    ]
