# Generated by Django 6.0.5 on 2026-06-10 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_statementstagingline_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(help_text='e.g., SIB_Savings_2026', max_length=100)),
                ('header_signature', models.CharField(help_text='e.g., Particulars,Txn Date,Balance', max_length=255)),
                ('date_index', models.IntegerField(default=0)),
                ('narration_index', models.IntegerField(default=1)),
                ('amount_index', models.IntegerField(default=2)),
                ('balance_index', models.IntegerField(default=3)),
                ('has_separate_dr_cr_columns', models.BooleanField(default=False)),
                ('debit_index', models.IntegerField(blank=True, null=True)),
                ('credit_index', models.IntegerField(blank=True, null=True)),
                ('date_format', models.CharField(default='%d-%m-%Y', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
