# Generated by Django 6.0.5 on 2026-06-13 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_userstatementtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatementtemplate',
            name='account',
            field=models.ForeignKey(blank=True, help_text='The specific bank account mapped directly to this parsing layout rule geometry.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statement_templates', to='ledger.account'),
        ),
        migrations.AlterField(
            model_name='userstatementtemplate',
            name='header_signature',
            field=models.CharField(help_text='JSON string mapping structural boundaries, e.g., {"UNIVERSAL_GEOMETRY": true, "withdrawals_max": 70}', max_length=255),
        ),
    ]
