# Generated by Django 6.0.5 on 2026-06-15 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0012_userstatementtemplate_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatementtemplate',
            name='amount_index',
        ),
        migrations.RemoveField(
            model_name='userstatementtemplate',
            name='has_separate_dr_cr_columns',
        ),
        migrations.RemoveField(
            model_name='userstatementtemplate',
            name='header_signature',
        ),
        migrations.AddField(
            model_name='userstatementtemplate',
            name='balance_x',
            field=models.FloatField(default=98.0, help_text='Expected horizontal start position % for Running Balances'),
        ),
        migrations.AddField(
            model_name='userstatementtemplate',
            name='credit_x',
            field=models.FloatField(default=60.0, help_text='Expected horizontal start position % for Credits'),
        ),
        migrations.AddField(
            model_name='userstatementtemplate',
            name='date_x',
            field=models.FloatField(default=10.0, help_text='Expected horizontal start position % for Date'),
        ),
        migrations.AddField(
            model_name='userstatementtemplate',
            name='debit_x',
            field=models.FloatField(default=52.0, help_text='Expected horizontal start position % for Debits'),
        ),
        migrations.AddField(
            model_name='userstatementtemplate',
            name='footer_lines_to_skip',
            field=models.IntegerField(default=0, help_text='Number of rows to drop at bottom of page'),
        ),
        migrations.AddField(
            model_name='userstatementtemplate',
            name='header_lines_to_skip',
            field=models.IntegerField(default=0, help_text='Number of rows to drop at top of page'),
        ),
        migrations.AddField(
            model_name='userstatementtemplate',
            name='matching_keyword',
            field=models.CharField(blank=True, default='', help_text='Lookup search anchor', max_length=100),
        ),
        migrations.AddField(
            model_name='userstatementtemplate',
            name='multiline_enabled',
            field=models.BooleanField(default=True, help_text='Toggles 2D state timeline buffer compilation'),
        ),
        migrations.AddField(
            model_name='userstatementtemplate',
            name='narration_x',
            field=models.FloatField(default=18.0, help_text='Expected horizontal start position % for Description'),
        ),
        migrations.AddField(
            model_name='userstatementtemplate',
            name='signature_json',
            field=models.TextField(blank=True, default='{}', help_text='Catch-all parameters JSON payload slot'),
        ),
        migrations.AddField(
            model_name='userstatementtemplate',
            name='y_tolerance',
            field=models.FloatField(default=3.0, help_text='Vertical character bounding box grouping window'),
        ),
        migrations.AlterField(
            model_name='userstatementtemplate',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Direct deterministic link to an explicit bank account.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statement_templates', to='ledger.account'),
        ),
        migrations.AlterField(
            model_name='userstatementtemplate',
            name='template_name',
            field=models.CharField(help_text='e.g., SBI_NRI_Stacked_2026', max_length=100),
        ),
    ]
