# Generated by Django 6.0.5 on 2026-06-15 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0013_remove_userstatementtemplate_amount_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatementtemplate',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Direct link to a specific bank account configuration.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statement_templates', to='ledger.account'),
        ),
        migrations.AlterField(
            model_name='userstatementtemplate',
            name='balance_x',
            field=models.FloatField(default=98.0, help_text='Horizontal percentage start point for Running Balances'),
        ),
        migrations.AlterField(
            model_name='userstatementtemplate',
            name='credit_x',
            field=models.FloatField(default=60.0, help_text='Horizontal percentage start point for Credits'),
        ),
        migrations.AlterField(
            model_name='userstatementtemplate',
            name='date_x',
            field=models.FloatField(default=10.0, help_text='Horizontal percentage start point for Date'),
        ),
        migrations.AlterField(
            model_name='userstatementtemplate',
            name='debit_x',
            field=models.FloatField(default=52.0, help_text='Horizontal percentage start point for Debits'),
        ),
        migrations.AlterField(
            model_name='userstatementtemplate',
            name='footer_lines_to_skip',
            field=models.IntegerField(default=0, help_text='Rows to discard at bottom of pages'),
        ),
        migrations.AlterField(
            model_name='userstatementtemplate',
            name='header_lines_to_skip',
            field=models.IntegerField(default=0, help_text='Rows to discard at top of pages'),
        ),
        migrations.AlterField(
            model_name='userstatementtemplate',
            name='matching_keyword',
            field=models.CharField(blank=True, default='', help_text='Lookup search anchor signature', max_length=100),
        ),
        migrations.AlterField(
            model_name='userstatementtemplate',
            name='multiline_enabled',
            field=models.BooleanField(default=True, help_text='Toggles the multi-line narration accumulator logic loop'),
        ),
        migrations.AlterField(
            model_name='userstatementtemplate',
            name='narration_x',
            field=models.FloatField(default=18.0, help_text='Horizontal percentage start point for Description'),
        ),
        migrations.AlterField(
            model_name='userstatementtemplate',
            name='signature_json',
            field=models.TextField(blank=True, default='{}', help_text="Dynamic parameters payload box, e.g., {'force_negative_balances': false, 'strip_all_zeros': true}"),
        ),
        migrations.AlterField(
            model_name='userstatementtemplate',
            name='y_tolerance',
            field=models.FloatField(default=3.0, help_text='Vertical line baseline grouping tolerance windows'),
        ),
    ]
