# Generated by Django 6.0.5 on 2026-06-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0014_alter_userstatementtemplate_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstatementtemplate',
            options={'verbose_name': 'User Statement Template', 'verbose_name_plural': 'User Statement Templates'},
        ),
        migrations.AlterField(
            model_name='userstatementtemplate',
            name='matching_keyword',
            field=models.CharField(blank=True, default='', help_text='Lookup search anchor signature matching bank layout profiles.', max_length=100),
        ),
        migrations.AlterField(
            model_name='userstatementtemplate',
            name='signature_json',
            field=models.JSONField(blank=True, default=dict, help_text="Central SSOT configuration box. Safely stores 'regex_patterns', 'opening_balance_markers', and 'system_noise_patterns' to eliminate code-level hardcoding anomalies completely."),
        ),
        migrations.AlterModelTable(
            name='userstatementtemplate',
            table='ledger_userstatementtemplate',
        ),
    ]
