# Generated by Django 6.0.5 on 2026-06-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0015_alter_userstatementtemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatementtemplate',
            name='header_mapping_json',
            field=models.JSONField(blank=True, default=dict, help_text="Stores column label aliases, e.g., {'date': ['Date', 'Txn Date'], 'debit': ['Debit', 'Withdrawal']}"),
        ),
        migrations.AlterField(
            model_name='userstatementtemplate',
            name='signature_json',
            field=models.JSONField(blank=True, default=dict, help_text='Stores regex_patterns, noise_patterns, and opening_balance_markers.'),
        ),
    ]
