# Generated by Django 6.0.5 on 2026-06-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0016_userstatementtemplate_header_mapping_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatementtemplate',
            name='parser_strategy_code',
            field=models.CharField(choices=[('STRICT_MATRIX', 'Strict Coordinate Matrix'), ('RELATIVE_SEQUENCE', 'Relative Text Sequences')], default='STRICT_MATRIX', help_text='Explicitly binds this layout template profile to a code-execution engine strategy.', max_length=50),
        ),
    ]
