# Generated by Django 6.0.5 on 2026-06-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0017_userstatementtemplate_parser_strategy_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementstagingline',
            name='cheque_ref_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
