# Generated by Django 6.0.5 on 2026-07-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0018_alter_statementstagingline_cheque_ref_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementingestregistry',
            name='admin_notes_count',
            field=models.IntegerField(default=0, help_text='Tracks system noise rows, statement footers, or non-financial note entries.'),
        ),
    ]
