# Generated by Django 6.0.5 on 2026-07-02 14:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0019_statementingestregistry_admin_notes_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rule_code', models.CharField(help_text='Unique custom rule code indicator string token: GR01, GR07', max_length=20, unique=True)),
                ('rule_title', models.CharField(max_length=255)),
                ('entry_type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], help_text='Target verification accounting vector direction', max_length=10)),
                ('rule_priority', models.IntegerField(default=1, help_text='Sorting weight priority indicator to settle keyword competition logs')),
                ('description_tags', models.JSONField(help_text='Array listing search trigger tracking tags keywords')),
                ('examples', models.JSONField(help_text='Array containing mock raw ledger transactions data')),
                ('rule_metadata', models.JSONField(default=dict, help_text='Stores: golden_rule_type, account_type, golden_rule_summary, category, subcategory')),
                ('is_active', models.BooleanField(default=True)),
                ('apply_to_ai', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Accounting Rule',
                'verbose_name_plural': 'Accounting Rules',
                'db_table': 'ledger_accountingrule',
                'ordering': ['rule_priority'],
            },
        ),
        migrations.CreateModel(
            name='MasterFinancialCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_type', models.CharField(choices=[('REGULAR', 'Standard Balance Sheet / Expense Item'), ('KNOWN_DEFAULT', 'Auto-Matched Known Rule Node'), ('SELF_TRANSFER', 'Inter-Account Internal Transfer Rule')], db_index=True, default='REGULAR', max_length=20)),
                ('sno', models.IntegerField(default=1)),
                ('act_category', models.CharField(help_text='e.g., Assets, Expenses, Income, Liabilities', max_length=100)),
                ('act_subcategory', models.CharField(help_text='e.g., Gold & Investments, Bank Balances, Cellular', max_length=100)),
                ('categories_items', models.CharField(help_text='Unique suffix string tracking token: Airtel-E, Swiggy-E, SBI-I', max_length=100)),
                ('dashboard_cat', models.CharField(help_text='Aggregated viewport target grouping configuration: Utilities, Dining', max_length=100)),
                ('match_key1', models.CharField(blank=True, db_index=True, help_text='Primary text query substring token', max_length=100, null=True)),
                ('match_key2', models.CharField(blank=True, help_text='Secondary verifying text constraint token', max_length=100, null=True)),
                ('from_bank_type', models.CharField(blank=True, max_length=100, null=True)),
                ('to_bank_type', models.CharField(blank=True, max_length=100, null=True)),
                ('transfer_value', models.CharField(blank=True, help_text='Maps legacy value column parameters', max_length=200, null=True)),
                ('self_account', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('concatenate', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_expense', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Master Financial Category',
                'verbose_name_plural': 'Master Financial Categories',
                'db_table': 'ledger_mastercategory',
                'ordering': ['category_type', 'act_category', 'categories_items'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applied_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mapped_entries', to='ledger.accountingrule')),
                ('journal_entry', models.OneToOneField(help_text='Links to your signed-amount double-entry row line', on_delete=django.db.models.deletion.CASCADE, related_name='category_mapping', to='ledger.journalentry')),
                ('assigned_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapped_entries', to='ledger.masterfinancialcategory')),
            ],
            options={
                'verbose_name': 'Journal Entry Mapping',
                'verbose_name_plural': 'Journal Entry Mappings',
                'db_table': 'ledger_entry_mapping',
            },
        ),
    ]
