# Generated by Django 6.0.5 on 2026-07-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0020_accountingrule_masterfinancialcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterfinancialcategory',
            name='sno',
            field=models.IntegerField(default=1, help_text='Stores legacy ID reference number tracks'),
        ),
    ]
