# Generated by Django 6.0.5 on 2026-07-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0021_alter_masterfinancialcategory_sno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterfinancialcategory',
            name='from_bank_type',
        ),
        migrations.RemoveField(
            model_name='masterfinancialcategory',
            name='match_key1',
        ),
        migrations.RemoveField(
            model_name='masterfinancialcategory',
            name='match_key2',
        ),
        migrations.RemoveField(
            model_name='masterfinancialcategory',
            name='to_bank_type',
        ),
        migrations.AddField(
            model_name='masterfinancialcategory',
            name='bank_types',
            field=models.JSONField(default=dict, help_text="Stores inter-bank routing details: {'from': '...', 'to': '...'}"),
        ),
        migrations.AddField(
            model_name='masterfinancialcategory',
            name='keys',
            field=models.JSONField(default=dict, help_text="Stores matching tokens: {'key1': '...', 'key2': '...'}"),
        ),
        migrations.AlterField(
            model_name='masterfinancialcategory',
            name='act_category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='masterfinancialcategory',
            name='act_subcategory',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='masterfinancialcategory',
            name='categories_items',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='masterfinancialcategory',
            name='dashboard_cat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='masterfinancialcategory',
            name='transfer_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
