# Generated by Django 6.0.5 on 2026-07-03 15:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0022_remove_masterfinancialcategory_from_bank_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WIPEvaluationMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_footprint_hash', models.CharField(db_index=True, help_text='Cloned hash state footprint linking back to Staging line', max_length=64)),
                ('raw_statement_date', models.DateField()),
                ('narration_normalized', models.TextField(help_text='Cleaned, lowercase text token scanning target')),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('is_split_component', models.BooleanField(default=False)),
                ('confidence_level', models.CharField(choices=[('HIGH', '100% Validated (Staged for Bulk Approval)'), ('ZERO', 'Validation Failed (Sent to Uncategorized Container)')], db_index=True, default='ZERO', max_length=10)),
                ('tier_1_passed', models.BooleanField(default=False)),
                ('tier_2_passed', models.BooleanField(default=False)),
                ('tier_3_passed', models.BooleanField(default=False)),
                ('evaluation_errors', models.JSONField(blank=True, default=list, help_text="Array listing gate block errors: ['UNMAPPED_PATTERN', 'MISALIGNED_HEADER']")),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.account')),
                ('applied_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.accountingrule')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.bank')),
                ('matched_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.masterfinancialcategory')),
                ('parent_wip', models.ForeignKey(blank=True, help_text='Points to the parent container when split across multiple headers', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_children', to='ledger.wipevaluationmatrix')),
                ('staging_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wip_records', to='ledger.statementstagingline')),
            ],
            options={
                'verbose_name': 'WIP Evaluation Matrix',
                'verbose_name_plural': 'WIP Evaluation Matrices',
                'db_table': 'ledger_wip_evaluation_matrix',
                'ordering': ['raw_statement_date'],
            },
        ),
    ]
