# Generated by Django 6.0.5 on 2026-07-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0023_wipevaluationmatrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionalVectorOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_category', models.CharField(help_text='e.g., Expenses, Charity', max_length=100)),
                ('expected_vector', models.CharField(choices=[('DEBIT', 'Debit (Outflow)'), ('CREDIT', 'Credit (Inflow)')], help_text='The directional vector this category normally expects.', max_length=10)),
                ('target_category', models.CharField(help_text='e.g., Income', max_length=100)),
                ('target_subcategory', models.CharField(help_text='e.g., Refunds & Reversals', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Directional Vector Override',
                'verbose_name_plural': 'Directional Vector Overrides',
                'db_table': 'tracker_directional_vector_override',
                'unique_together': {('source_category', 'expected_vector')},
            },
        ),
    ]
