# Generated by Django 6.0.5 on 2026-07-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0024_directionalvectoroverride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directionalvectoroverride',
            name='expected_vector',
            field=models.CharField(choices=[('DEBIT', 'Debit (Outflow)'), ('CREDIT', 'Credit (Inflow)')], default='DEBIT', help_text='The directional vector this category normally expects.', max_length=10),
        ),
    ]
