# Generated by Django 6.0.5 on 2026-07-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0025_alter_directionalvectoroverride_expected_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='wipevaluationmatrix',
            name='confidence_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wipevaluationmatrix',
            name='resolved_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wipevaluationmatrix',
            name='resolved_subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wipevaluationmatrix',
            name='t1_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wipevaluationmatrix',
            name='t1_subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wipevaluationmatrix',
            name='t2_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wipevaluationmatrix',
            name='t2_subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wipevaluationmatrix',
            name='t3_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wipevaluationmatrix',
            name='t3_subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wipevaluationmatrix',
            name='confidence_level',
            field=models.CharField(default='ZERO', max_length=10),
        ),
    ]
