# Generated by Django 6.0.5 on 2026-07-12 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0026_wipevaluationmatrix_confidence_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='transaction',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='evaluation_matrix_snapshot',
            field=models.JSONField(default=dict, help_text='Stores: {t1_cat, t2_cat, t3_cat, resolved_cat, resolved_sub, applied_rule}'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='row_identifier',
            field=models.CharField(db_index=True, default='MIGRATION_FALLBACK_HEX', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentry',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelTable(
            name='journalentry',
            table='tracker_journal_entry',
        ),
    ]
