# Generated by Django 6.0.5 on 2026-07-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0027_remove_journalentry_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='journalentry',
            table='ledger_journal_entry',
        ),
    ]
