# Generated by Django 6.0.5 on 2026-07-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0028_alter_journalentry_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='wipevaluationmatrix',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pending Ledger Sync'), ('COMPLETED', 'Synced to Ledger')], default='PENDING', max_length=20),
        ),
    ]
