# Generated by Django 6.0.5 on 2026-07-24 13:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0029_wipevaluationmatrix_processing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Swiggy Auto-Classify', max_length=255)),
                ('pattern', models.CharField(db_index=True, help_text='Search anchor e.g. SWIGGY', max_length=255)),
                ('rule_type', models.CharField(choices=[('CONTAINS', 'Contains Pattern'), ('EXACT', 'Exact Match'), ('REGEX', 'Regex Pattern')], default='CONTAINS', max_length=20)),
                ('target_category', models.CharField(max_length=100)),
                ('target_subcategory', models.CharField(max_length=100)),
                ('priority', models.IntegerField(default=10, help_text='Higher priority rules run first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_from_manual_override', models.BooleanField(default=True)),
                ('match_count', models.IntegerField(default=0, help_text='Total transactions classified by this rule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ledger_classification_rule',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
