# Generated by Django 6.0.5 on 2026-07-25 10:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0030_classificationrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificationrule',
            name='pattern',
        ),
        migrations.AddField(
            model_name='classificationrule',
            name='patterns',
            field=models.JSONField(blank=True, default=list, help_text='List of search anchors, e.g. ["SWIGGY", "ZOMATO"]'),
        ),
        migrations.CreateModel(
            name='TaxonomyTree',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ledger_taxonomy_tree',
                'ordering': ['category', 'display_order', 'subcategory'],
                'unique_together': {('category', 'subcategory')},
            },
        ),
    ]
