# Generated by Django 6.0.5 on 2026-07-25 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0031_remove_classificationrule_pattern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationrule',
            name='last_executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classificationrule',
            name='rule_code',
            field=models.CharField(blank=True, help_text='Unique shorthand code mapped to Node 99 metadata tracking.', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='classificationrule',
            name='taxonomy',
            field=models.ForeignKey(blank=True, help_text='Target taxonomy node in TaxonomyTree', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classification_rules', to='ledger.taxonomytree'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='classification_status',
            field=models.CharField(choices=[('INITIAL', 'Initial Auto-Classification'), ('RECLASSIFIED', 'Manually Reclassified'), ('SUSPENSE', 'Pending Suspense')], db_index=True, default='INITIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_reclassified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='classificationrule',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='classificationrule',
            name='target_category',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='classificationrule',
            name='target_subcategory',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='evaluation_matrix_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Stores: {t1_cat, t2_cat, t3_cat, resolved_cat, resolved_sub, applied_rule, audit_history}'),
        ),
        migrations.AddIndex(
            model_name='classificationrule',
            index=models.Index(fields=['is_active', '-priority'], name='ledger_clas_is_acti_8f2a0d_idx'),
        ),
        migrations.AddIndex(
            model_name='classificationrule',
            index=models.Index(fields=['rule_code'], name='ledger_clas_rule_co_0aaa0a_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['row_identifier', 'account'], name='ledger_jour_row_ide_b086f6_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['account', 'is_reclassified'], name='ledger_jour_account_2ee2b7_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['classification_status'], name='ledger_jour_classif_fb25db_idx'),
        ),
    ]
