# Generated by Django 6.0.5 on 2026-07-26 00:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0032_classificationrule_last_executed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action_type', models.CharField(db_index=True, max_length=50)),
                ('target_table', models.CharField(db_index=True, max_length=100)),
                ('account_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('row_identifier', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('new_state', models.JSONField(blank=True, default=dict)),
                ('applied_rule_code', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ledger_audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['account_id', 'action_type'], name='ledger_audi_account_f680b4_idx'), models.Index(fields=['target_table', 'row_identifier'], name='ledger_audi_target__f52e6b_idx'), models.Index(fields=['timestamp'], name='ledger_audi_timesta_9b96d3_idx')],
            },
        ),
    ]
