# Generated by Django 6.0.5 on 2026-07-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0033_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='remarks',
            field=models.CharField(blank=True, help_text='Standardized audit remark string with directional By/To prefix.', max_length=500, null=True),
        ),
    ]
