# Generated by Django 6.0.5 on 2026-07-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0034_journalentry_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='remarks',
            field=models.JSONField(blank=True, default=dict, help_text='Stores: {display_text, directional_prefix, target_account_name, payee, upi_ref, user_note, rule_code}'),
        ),
    ]
