# Generated by Django 6.0.5 on 2026-08-04 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0035_alter_journalentry_remarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classificationrule',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='classificationrule',
            name='ledger_clas_is_acti_8f2a0d_idx',
        ),
        migrations.RemoveIndex(
            model_name='classificationrule',
            name='ledger_clas_rule_co_0aaa0a_idx',
        ),
        migrations.AlterField(
            model_name='classificationrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classificationrule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='classificationrule',
            name='match_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classificationrule',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='classificationrule',
            name='patterns',
            field=models.JSONField(blank=True, default=list, help_text="JSON list of clean multi-token pattern strings e.g. ['MOHANAN P', 'SWIGGY YESPAY']"),
        ),
        migrations.AlterField(
            model_name='classificationrule',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='classificationrule',
            name='rule_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='classificationrule',
            name='rule_type',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], default='Debit', max_length=10),
        ),
        migrations.AlterField(
            model_name='classificationrule',
            name='target_category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='classificationrule',
            name='target_subcategory',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='classificationrule',
            name='taxonomy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.taxonomytree'),
        ),
        migrations.RemoveField(
            model_name='classificationrule',
            name='last_executed_at',
        ),
    ]
