# Generated by Django 6.0.5 on 2026-08-05 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0036_alter_classificationrule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingrule',
            name='taxonomy',
            field=models.ForeignKey(blank=True, db_column='taxonomy_id', help_text='Master taxonomy node authority governing this rule', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_rules', to='ledger.taxonomytree'),
        ),
    ]
