# Generated by Django 6.0.5 on 2026-08-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0037_accountingrule_taxonomy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='classification_status',
            field=models.CharField(choices=[('INITIAL', 'Initial Auto-Classification'), ('RECLASSIFIED', 'Manually Reclassified'), ('SUSPENSE', 'Pending Suspense'), ('AUTO_SWEPT', 'Auto-Swept by Rule Engine'), ('CONFIRMED', 'Audited & Confirmed'), ('SPLIT', 'Split Transaction'), ('SYSTEM_INTERNAL', 'System Contra / Inter-Account Transfer')], db_index=True, default='INITIAL', max_length=20),
        ),
    ]
