# Generated by Django 6.0.5 on 2026-08-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0038_alter_journalentry_classification_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('row_identifier', 'account'), name='uq_row_identifier_account'),
        ),
    ]
