# Generated by Django 6.0.5 on 2026-08-12 16:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0039_journalentry_uq_row_identifier_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSubLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_code', models.CharField(db_index=True, help_text='Human-readable code, e.g., AST-RE-001 or AST-NPS-002', max_length=32, unique=True)),
                ('name', models.CharField(help_text="Display title, e.g., 'Ulloor Plot & House'", max_length=255)),
                ('category', models.CharField(choices=[('REAL_ESTATE', 'Real Estate & Land'), ('FIXED_DEPOSIT', 'Fixed Deposit (FD)'), ('RECURRING_DEPOSIT', 'Recurring Deposit (RD)'), ('MARKET_INVESTMENT', 'Stocks, Mutual Funds & ETFs'), ('PENSION_RETIREMENT', 'Pension & Retirement (NPS, PPF, EPF)'), ('INSURANCE_PLAN', 'Life & Endowment Insurance'), ('VEHICLE', 'Vehicles & Transport'), ('PRECIOUS_METALS', 'Gold, Silver & SGBs'), ('PERSONAL_RECEIVABLE', 'Personal Loan Given / Receivable')], db_index=True, max_length=32)),
                ('acquisition_date', models.DateField(default=django.utils.timezone.now)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('current_valuation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valuation_updated_at', models.DateTimeField(auto_now=True)),
                ('ownership_type', models.CharField(choices=[('INDIVIDUAL', 'Individual / Sole Owner'), ('JOINT', 'Joint Ownership'), ('FAMILY', 'Family Trust / Group'), ('BUSINESS', 'Business Entity')], default='INDIVIDUAL', max_length=20)),
                ('ownership_share_pct', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Holding'), ('MATURED', 'Matured'), ('LIQUIDATED', 'Liquidated / Closed'), ('SOLD', 'Sold / Transferred'), ('WRITTEN_OFF', 'Written Off')], db_index=True, default='ACTIVE', max_length=20)),
                ('metadata_payload', models.JSONField(blank=True, default=dict, help_text='Stores category-specific attributes (deed numbers, PRAN, survey numbers, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_gl_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subledger_assets', to='ledger.account')),
            ],
            options={
                'verbose_name': 'Asset Sub-Ledger Record',
                'verbose_name_plural': 'Asset Sub-Ledger Registry',
                'db_table': 'ledger_asset_subledger',
            },
        ),
        migrations.CreateModel(
            name='AssetOperationalAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('PROPERTY_TAX', 'Local Body Property Tax (Panchayat/Corporation)'), ('LAND_REVENUE_TAX', 'Land Revenue Tax (Thandaper)'), ('ELECTRICITY', 'Electricity Board (e.g., KSEB)'), ('WATER', 'Water Authority (e.g., KWA)'), ('BUILDING_MAINTENANCE', 'Resident Association / Maintenance'), ('INSURANCE', 'Asset / Liability Insurance'), ('GAS', 'Piped Gas / LPG Connection')], db_index=True, max_length=32)),
                ('provider_name', models.CharField(help_text='e.g., KSEB, KWA, Trivandrum Corporation, Revenue Dept', max_length=128)),
                ('consumer_identifier', models.CharField(help_text='Consumer No / Building Assessment No / Thandaper No', max_length=64)),
                ('meter_number', models.CharField(blank=True, max_length=64, null=True)),
                ('matching_keyword', models.CharField(blank=True, help_text="Narration pattern to assist matching algorithm, e.g., 'KSEB 1156890012'", max_length=128, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_accounts', to='ledger.assetsubledger')),
            ],
            options={
                'verbose_name': 'Operational Utility / Tax Account',
                'verbose_name_plural': 'Operational Utility / Tax Accounts',
                'db_table': 'ledger_asset_operational_account',
            },
        ),
        migrations.CreateModel(
            name='AssetComplianceSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="e.g., 'Panchayat Land Tax 2026-27' or 'NPS Monthly SIP'", max_length=255)),
                ('schedule_type', models.CharField(choices=[('PROPERTY_TAX_DUE', 'Property Tax Due'), ('LAND_TAX_DUE', 'Land Revenue Tax Due'), ('UTILITY_BILL', 'Utility Bill Payment'), ('SIP_DUE', 'Investment / Pension SIP Installment'), ('PREMIUM_DUE', 'Insurance Premium'), ('FD_MATURITY', 'Deposit Maturity Payout')], db_index=True, max_length=32)),
                ('recurrence_pattern', models.CharField(choices=[('ONE_OFF', 'One-Time / Ad-Hoc'), ('MONTHLY', 'Monthly'), ('BIMONTHLY', 'Bi-Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half-Yearly'), ('ANNUALLY', 'Annually')], default='MONTHLY', max_length=20)),
                ('due_date', models.DateField(db_index=True)),
                ('expected_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('advance_notice_days', models.PositiveIntegerField(default=10, help_text='Days in advance to alert on dashboard')),
                ('is_paid', models.BooleanField(db_index=True, default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('linked_row_identifier', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('operational_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='ledger.assetoperationalaccount')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_schedules', to='ledger.assetsubledger')),
            ],
            options={
                'verbose_name': 'Compliance Schedule / Reminder',
                'verbose_name_plural': 'Compliance Schedules & Reminders',
                'db_table': 'ledger_asset_compliance_schedule',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetTransactionMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_identifier', models.CharField(blank=True, db_index=True, help_text='Hex fingerprint matching ledger_journal_entry. Null if cash entry.', max_length=64, null=True)),
                ('is_cash_entry', models.BooleanField(default=False, help_text='True if transaction occurred offline via cash without a bank row.')),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_purpose', models.CharField(help_text='e.g., PROPERTY_TAX, UTILITY_BILL, SIP_CONTRIBUTION, CAPITAL_IMPROVEMENT', max_length=64)),
                ('user_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_mappings', to='ledger.assetsubledger')),
                ('operational_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.assetoperationalaccount')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.assetcomplianceschedule')),
            ],
            options={
                'verbose_name': 'Asset Transaction Mapping',
                'verbose_name_plural': 'Asset Transaction Mappings',
                'db_table': 'ledger_asset_transaction_mapping',
            },
        ),
        migrations.AddIndex(
            model_name='assetsubledger',
            index=models.Index(fields=['category', 'status'], name='ledger_asse_categor_0ea109_idx'),
        ),
        migrations.AddIndex(
            model_name='assetsubledger',
            index=models.Index(fields=['asset_code'], name='ledger_asse_asset_c_1f4adb_idx'),
        ),
    ]
