# Generated by Django 6.0.5 on 2026-08-13 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0040_assetsubledger_assetoperationalaccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsubledger',
            name='linked_gl_account',
            field=models.ForeignKey(help_text='Chart of Accounts Taxonomy category for General Ledger alignment', on_delete=django.db.models.deletion.PROTECT, related_name='subledger_assets', to='ledger.taxonomytree'),
        ),
    ]
