# Generated by Django 6.0.5 on 2026-08-13 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0041_alter_assetsubledger_linked_gl_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsubledger',
            name='linked_gl_account',
            field=models.ForeignKey(blank=True, help_text='Chart of Accounts Taxonomy category for General Ledger alignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subledger_assets', to='ledger.taxonomytree'),
        ),
    ]
