# Generated by Django 6.0.5 on 2026-08-15 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0042_alter_assetsubledger_linked_gl_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsubledger',
            name='asset_code',
            field=models.CharField(db_index=True, help_text='Human-readable code, e.g., AST-RE-001 or AST-FD-002', max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='System key code, e.g., REAL_ESTATE, FIXED_DEPOSIT', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display label, e.g., Real Estate & Land, Fixed Deposit (FD)', max_length=100)),
                ('default_taxonomy_category', models.CharField(default='Asset', help_text='Primary taxonomy class, e.g., Asset, Liability', max_length=100)),
                ('default_taxonomy_subcategory', models.CharField(help_text='Exact subcategory matching Dashboard matrix, e.g., Real Estate, Fixed Deposits', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_gl_account', models.ForeignKey(blank=True, help_text='Default Chart of Accounts node for this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_categories', to='ledger.taxonomytree')),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
                'db_table': 'ledger_asset_category',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='assetsubledger',
            name='asset_category',
            field=models.ForeignKey(blank=True, help_text='Foreign key to dynamic AssetCategory table', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subledger_assets', to='ledger.assetcategory'),
        ),
        migrations.AddIndex(
            model_name='assetsubledger',
            index=models.Index(fields=['asset_category', 'status'], name='ledger_asse_asset_c_143662_idx'),
        ),
    ]
