# Generated by Django 6.0.5 on 2026-08-17 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0044_vendor_assetsubledger_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wipevaluationmatrix',
            name='t1_category',
        ),
        migrations.RemoveField(
            model_name='wipevaluationmatrix',
            name='t1_subcategory',
        ),
        migrations.RemoveField(
            model_name='wipevaluationmatrix',
            name='t2_category',
        ),
        migrations.RemoveField(
            model_name='wipevaluationmatrix',
            name='t2_subcategory',
        ),
        migrations.RemoveField(
            model_name='wipevaluationmatrix',
            name='t3_category',
        ),
        migrations.RemoveField(
            model_name='wipevaluationmatrix',
            name='t3_subcategory',
        ),
        migrations.RemoveField(
            model_name='wipevaluationmatrix',
            name='tier_1_passed',
        ),
        migrations.RemoveField(
            model_name='wipevaluationmatrix',
            name='tier_2_passed',
        ),
        migrations.RemoveField(
            model_name='wipevaluationmatrix',
            name='tier_3_passed',
        ),
        migrations.AddField(
            model_name='wipevaluationmatrix',
            name='matrix_evaluation',
            field=models.JSONField(blank=True, default=dict, help_text='JSON payload containing t1..t5 tier breakdowns and system certainty scores'),
        ),
        migrations.AlterField(
            model_name='wipevaluationmatrix',
            name='confidence_level',
            field=models.CharField(choices=[('HIGH', '100% Validated (Staged for Bulk Approval)'), ('ZERO', 'Validation Failed (Sent to Uncategorized Container)')], db_index=True, default='ZERO', max_length=10),
        ),
        migrations.AlterField(
            model_name='wipevaluationmatrix',
            name='evaluation_errors',
            field=models.JSONField(blank=True, default=list, help_text='Array listing gate block errors'),
        ),
        migrations.AlterField(
            model_name='wipevaluationmatrix',
            name='parent_wip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_children', to='ledger.wipevaluationmatrix'),
        ),
    ]
