# Generated by Django 6.0.5 on 2026-08-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0045_remove_wipevaluationmatrix_t1_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'ordering': ['id'], 'verbose_name': 'Asset & Subledger Category', 'verbose_name_plural': 'Asset & Subledger Categories'},
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='category_type',
            field=models.CharField(choices=[('ASSET', 'Asset (Balance Sheet)'), ('INCOME', 'Income Stream (P&L Inflow)'), ('EXPENSE', 'Expense Cost Center (P&L Outflow)')], db_index=True, default='ASSET', help_text='Classification group: ASSET (Balance Sheet), INCOME (P&L), or EXPENSE (P&L)', max_length=20),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='code',
            field=models.CharField(db_index=True, help_text='System key code, e.g., REAL_ESTATE, RENTAL_STREAM, VENDOR_MERCHANT', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='default_taxonomy_category',
            field=models.CharField(default='Asset', help_text='Primary taxonomy class, e.g., Asset, Income, Expense, Liability', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='default_taxonomy_subcategory',
            field=models.CharField(help_text='Exact subcategory matching Dashboard matrix, e.g., Real Estate, Rental Income, Charity', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='name',
            field=models.CharField(help_text='Display label, e.g., Real Estate & Land, Property Rental Stream', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetsubledger',
            name='category',
            field=models.CharField(choices=[('REAL_ESTATE', 'Real Estate & Land'), ('FIXED_DEPOSIT', 'Fixed Deposit (FD)'), ('RECURRING_DEPOSIT', 'Recurring Deposit (RD)'), ('MARKET_INVESTMENT', 'Stocks, Mutual Funds & ETFs'), ('PENSION_RETIREMENT', 'Pension & Retirement (NPS, PPF, EPF)'), ('INSURANCE_PLAN', 'Life & Endowment Insurance'), ('VEHICLE', 'Vehicles & Transport'), ('PRECIOUS_METALS', 'Gold, Silver & SGBs'), ('PERSONAL_RECEIVABLE', 'Personal Loan Given / Receivable'), ('RENTAL_STREAM', 'Rental Income Stream'), ('DIVIDEND_FOLIO', 'Dividend & Yield Stream'), ('RETAINER_CONTRACT', 'Client Retainer / Service Contract'), ('VENDOR_MERCHANT', 'Merchant / Service Provider'), ('CHARITY_RECIPIENT', 'Charity / 80G Recipient'), ('PROJECT_COST_CENTER', 'Project / Renovation Cost Center')], db_index=True, max_length=32),
        ),
    ]
