# Generated by Django 6.0.5 on 2026-08-18 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0046_alter_assetcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcategory',
            name='category_type',
            field=models.CharField(choices=[('ASSET', 'Asset (Balance Sheet)'), ('INCOME', 'Income Stream (P&L Inflow)'), ('EXPENSE', 'Expense Cost Center (P&L Outflow)')], db_index=True, default='ASSET', max_length=20),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='default_taxonomy_category',
            field=models.CharField(default='Asset', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='default_taxonomy_subcategory',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='linked_gl_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_categories', to='ledger.taxonomytree'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assetsubledger',
            name='category',
            field=models.CharField(choices=[('REAL_ESTATE', 'Real Estate & Land'), ('FIXED_DEPOSIT', 'Fixed Deposit (FD)'), ('RECURRING_DEPOSIT', 'Recurring Deposit (RD)'), ('MARKET_INVESTMENT', 'Stocks, Mutual Funds & ETFs'), ('PENSION_RETIREMENT', 'Pension & Retirement'), ('INSURANCE_PLAN', 'Life & Endowment Insurance'), ('VEHICLE', 'Vehicles & Transport'), ('PRECIOUS_METALS', 'Gold, Silver & SGBs'), ('PERSONAL_RECEIVABLE', 'Personal Loan Given'), ('RENTAL_STREAM', 'Property Rental Stream'), ('DIVIDEND_FOLIO', 'Dividend & Yield Stream'), ('VENDOR_MERCHANT', 'Merchant / Service Provider'), ('CHARITY_RECIPIENT', 'Charity / 80G Recipient')], db_index=True, max_length=32),
        ),
    ]
