# Generated by Django 6.0.5 on 2026-08-18 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0047_alter_assetcategory_category_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsubledger',
            name='parent_asset',
            field=models.ForeignKey(blank=True, help_text='Parent asset generating this income or incurring this expense (e.g. SBI-NRE1 FD generating Interest)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_streams', to='ledger.assetsubledger'),
        ),
    ]
