# Generated by Django 6.0.5 on 2026-08-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0048_assetsubledger_parent_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsubledger',
            name='acquisition_funding_source',
            field=models.CharField(choices=[('BANK_STAGING', '🏦 Bank Line (Reconciled via Staging)'), ('DIRECT_CASH', '💵 Direct Cash / Manual (Bank Row Missing)'), ('HISTORICAL_OPENING', '📜 Historical / Opening Balance (Pre-System Asset)'), ('GIFTS_INHERITANCE', '🎁 Gift / Family Inheritance (Non-Cash Capital)'), ('OTHER', '📁 Other / Manual Adjustment')], db_index=True, default='BANK_STAGING', help_text='Tracks how the acquisition cost baseline was funded or if bank statement line is missing', max_length=30),
        ),
        migrations.AddField(
            model_name='assetsubledger',
            name='is_bank_row_missing',
            field=models.BooleanField(default=False, help_text='True if asset was acquired via cash, opening balance, or unbanked transaction'),
        ),
        migrations.AddIndex(
            model_name='assetsubledger',
            index=models.Index(fields=['acquisition_funding_source'], name='ledger_asse_acquisi_87238e_idx'),
        ),
    ]
