# Generated by Django 6.1 on 2026-08-24 09:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0049_assetsubledger_acquisition_funding_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawEmailPayload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(default='POWER_AUTOMATE', max_length=50)),
                ('encrypted_payload', models.TextField(help_text='AES-256 encrypted payload string')),
                ('payload_hash', models.CharField(db_index=True, help_text='SHA-256 hash of raw email body/metadata for deduplication', max_length=64, unique=True)),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('DECRYPTED', 'Decrypted'), ('STAGED', 'Sent to Staging'), ('DUPLICATE', 'Duplicate Skipped'), ('FAILED', 'Failed Processing')], default='RECEIVED', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'raw_email_payloads',
                'ordering': ['-created_at'],
            },
        ),
    ]
