# Generated by Django 6.1 on 2026-08-24 09:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0050_rawemailpayload'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawemailpayload',
            name='account_last4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rawemailpayload',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='rawemailpayload',
            name='decrypted_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawemailpayload',
            name='has_attachments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawemailpayload',
            name='merchant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rawemailpayload',
            name='txn_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='rawemailpayload',
            name='txn_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rawemailpayload',
            name='upi_ref',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='rawemailpayload',
            name='encrypted_payload',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rawemailpayload',
            name='payload_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='rawemailpayload',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('DECRYPTED', 'Decrypted'), ('PARSED', 'Parsed'), ('FAILED', 'Failed'), ('DUPLICATE', 'Duplicate')], default='RECEIVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='rawemailpayload',
            name='subject',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.IntegerField(help_text='Size in bytes')),
                ('file_path', models.FileField(upload_to='email_attachments/%Y/%m/')),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ledger.rawemailpayload')),
            ],
            options={
                'db_table': 'email_attachments',
            },
        ),
    ]
