# Generated by Django 6.1 on 2026-08-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0051_rawemailpayload_account_last4_rawemailpayload_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawemailpayload',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rawemailpayload',
            name='email_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='rawemailpayload',
            name='email_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rawemailpayload',
            name='headers_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
