# Generated by Django 6.0.5 on 2026-08-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0052_rawemailpayload_bank_name_rawemailpayload_email_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawemailpayload',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawemailpayload',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False, help_text='True when reconciled with ledger_statementstagingline'),
        ),
        migrations.AddField(
            model_name='rawemailpayload',
            name='taxonomy_payload',
            field=models.JSONField(blank=True, default=dict, help_text='JSON containing account_match, taxonomy IDs, normalized_txn, and audit_trail'),
        ),
        migrations.AlterField(
            model_name='rawemailpayload',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('DECRYPTED', 'Decrypted'), ('PARSED', 'Parsed'), ('FAILED', 'Failed'), ('DUPLICATE', 'Duplicate'), ('COMPLETED', 'Completed')], default='RECEIVED', max_length=20),
        ),
    ]
