# Generated by Django 6.0.5 on 2026-08-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0053_rawemailpayload_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawemailpayload',
            name='is_staged_for_matching',
            field=models.BooleanField(db_index=True, default=False, help_text='True when ready for reconciling with ledger_statementstagingline'),
        ),
        migrations.AddField(
            model_name='rawemailpayload',
            name='staged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawemailpayload',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('DECRYPTED', 'Decrypted'), ('PARSED', 'Parsed'), ('STAGED', 'Staged for Matching'), ('FAILED', 'Failed'), ('DUPLICATE', 'Duplicate'), ('COMPLETED', 'Completed')], default='RECEIVED', max_length=20),
        ),
    ]
