# Generated by Django 6.0.5 on 2026-08-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0054_rawemailpayload_is_staged_for_matching_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawemailpayload',
            name='staging_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Structured metadata snapshot evaluated during statement matching', null=True),
        ),
    ]
