# Generated by Django 6.0.5 on 2026-09-06 15:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0055_rawemailpayload_staging_payload'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentInboxItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(db_index=True, max_length=128)),
                ('attachment_id', models.CharField(max_length=255, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=512)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('doc_type', models.CharField(choices=[('STATEMENT', 'Bank Statement'), ('TERM_DEPOSIT', 'Term Deposit (FD/RD)'), ('UNKNOWN', 'Unclassified Document')], db_index=True, default='UNKNOWN', max_length=32)),
                ('status', models.CharField(choices=[('INBOX', 'Pending in Inbox'), ('PROCESSING', 'Active in Staging'), ('COMPLETED', 'Extracted & Processed'), ('ARCHIVED', 'Archived / Discarded')], db_index=True, default='INBOX', max_length=32)),
                ('sender', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('account_hint', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-received_date', '-created_at'],
            },
        ),
    ]
