# Generated by Django 6.1 on 2026-09-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0056_documentinboxitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentinboxitem',
            name='attachment_hash',
            field=models.CharField(db_index=True, default='', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='documentinboxitem',
            name='attachment_id',
            field=models.TextField(),
        ),
    ]
