# Generated by Django 6.1 on 2026-09-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0057_documentinboxitem_attachment_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentinboxitem',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentinboxitem',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
