import os
import django
import json

# Setup Django standalone execution context
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "core.settings")
django.setup()

from django.db import transaction
from backend.tracker.models.models import AccountingRule

RAW_RULES_EXPORT = [
    (
        "GR01",
        "Debit the receiver",
        "Personal",
        "None",
        "Asset",
        "Debit",
        "Asset",
        "Personal Assets",
        '["receiver", "given", "receive"]',
        '["Received cash", "Payment received"]',
        1,
        "When a person receives value, debit their account.",
    ),
    (
        "GR02",
        "Credit the giver",
        "Personal",
        "None",
        "Liability",
        "Credit",
        "Liability",
        "Personal Liabilities",
        '["giver", "given", "payment"]',
        '["Paid cash", "Payment made"]',
        2,
        "When a person gives value, credit their account.",
    ),
    (
        "GR03",
        "Debit what comes in",
        "Real",
        "None",
        "Asset",
        "Debit",
        "Asset",
        "Real Assets",
        '["purchase", "bought", "received"]',
        '["Bought equipment", "Received goods"]',
        3,
        "Debit the asset that comes into the business.",
    ),
    (
        "GR04",
        "Credit what goes out",
        "Real",
        "None",
        "Asset",
        "Credit",
        "Asset",
        "Real Assets",
        '["sold", "disposed"]',
        '["Sold equipment", "Goods disposed"]',
        4,
        "Credit the asset when it goes out of the business.",
    ),
    (
        "GR05",
        "Debit all expenses and losses",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Operational Expenses",
        '["expense", "loss", "cost", "payment"]',
        '["Electricity bill", "Repair cost"]',
        5,
        "Debit all expenses and losses.",
    ),
    (
        "GR06",
        "Credit all incomes and gains",
        "Nominal",
        "None",
        "Income",
        "Credit",
        "Income",
        "Revenue",
        '["income", "sales", "revenue", "gain", "int on fd inr", "interest credit", "int trf", "sbint", "int.pd", "43438795987"]',
        '["Sales income", "Interest received"]',
        6,
        "Credit all incomes and gains.",
    ),
    (
        "GR07",
        "Debit bank charges and fees",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Bank Charges",
        '["bank charge", "fail chrg", "debit mandate", "fee", "maint", "sms", "service", "amc", "cash wdl service", "charges for rtgs", "chrg", "chrg/imps", "chrg/min bal", "commission", "debit card amc", "imps charges", "insufficient bal", "mandate fail chrg", "min bal", "minimum balance charges", "sms charges", "wdl service", "wdlservice"]',
        '["SMS alert fee", "Bank maintenance charge", "Service fee"]',
        7,
        "Debit all expenses and losses, including bank-related charges and fees.",
    ),
    (
        "GR08A",
        "Debit temple and religious donations",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Temple Donations",
        '["mandir", "church", "mosque", "religious", "mukalvata", "SREE PADMANABHASWAMY", "Temple donation", "Religious offering", "Mukalvata payment", "sree panchami devi temple", "travancore devaswom board", "devasam"]',
        '["Temple donation", "Religious offering"]',
        8,
        "Debit all expenses and losses, including religious and temple-related donations.",
    ),
    (
        "GR09",
        "Debit gold purchase and jewellery",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Gold Purchase",
        '["bhima", "bhima jewellers and diamonds", "bhima jewellery", "joyalukkas", "kalyan"]',
        '["Bhima jewellers purchase", "Gold purchase at Joyalukkas", "Kalyan jewellery payment"]',
        9,
        "Debit all expenses related to gold and jewellery purchase",
    ),
    (
        "GR10",
        "Investment in  Life Insurance",
        "Real",
        "None",
        "Asset",
        "Debit",
        "Asset",
        "Investment",
        '["ageasfddc", "sbi-life", "sbi life insurance", "hdfc-life", "sbin2250080903300097160044302"]',
        '["SBI Life insurance premium", "Investment in SBI Life", "SBI Life policy payment"]',
        10,
        "Debit asset account for investments in SBI Life insurance.",
    ),
    (
        "GR11",
        "Debit utility and bill payments",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Utility Bills",
        '["airtel", "disney hotsta", "air fiber", "jio", "government of kerala bill", "kerala state electricity", "kseb", "kerala state road transport", "ksstm", "kwat", "water bill", "electricity", "mobile recharge", "internet bill"]',
        '["Airtel mobile payment", "Kerala electricity bill", "Jio recharge", "Water bill payment"]',
        11,
        "Debit all expenses related to utility bills including mobile, electricity, water, and transport charges.",
    ),
    (
        "GR12",
        "Debit entertainment expenses",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Entertainment",
        '["amazon prime", "disney hotstar", "airtel", "air fiber", "jio", "streaming", "subscription", "netflix"]',
        '["Amazon Prime subscription", "Disney Hotstar payment", "Airtel internet charge"]',
        12,
        "Debit all expenses related to entertainment and subscriptions.",
    ),
    (
        "GR13",
        "Debit education and trust donations",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Education & Donations",
        '["jain trust", "jain university", "jainonline", "jainuniversi"]',
        '["Donation to Jain Trust", "Jain University fees"]',
        13,
        "Debit all expenses related to education fees and donations to trusts.",
    ),
    (
        "GR14",
        "Debit fuel and transport expenses",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Fuel and Transport",
        '["fuel", "petrol", "diesel", "gasoline", "transport", "vehicle", "bharat petroleum", "indian oil", "fuel", "fuels", "petrol", "shell", "hindustan petroleum", "hpcl", "iocl", "bunk", "petrolpump", "NAGARAJAN AND SONS", "nagarajan s"]',
        '["Fuel for vehicle", "Petrol purchase", "Diesel charges"]',
        14,
        "Debit all expenses related to fuel and transport.",
    ),
    (
        "GR15",
        "Investment in Health Insurance",
        "Real",
        "None",
        "Asset",
        "Debit",
        "Asset",
        "Insurance",
        '["arogya policy", "health insurance", "health policy"]',
        '["Arogya health insurance premium", "Health insurance payment"]',
        15,
        "Debit asset account for investments in health insurance policies.",
    ),
    (
        "GR16",
        "Investment in Pension Scheme",
        "Real",
        "None",
        "Asset",
        "Debit",
        "Asset",
        "Investment",
        '["national pension scheme", "nps cams", "nps"]',
        '["NPS contribution", "NPS CAMS payment"]',
        16,
        "Debit asset account for investments in pension schemes.",
    ),
    (
        "GR17",
        "Debit groceries and shopping expenses",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Groceries and Shopping",
        '["amazon india", "amazon pay", "amazon seller", "amazonupi", "amznplpvrv", "bazaar pvt lt", "crossword", "lulu", "garments", "lulu international", "lulutrivandrum", "margin free", "pos", "pos atm purch", "pothys", "premier office", "ramachandran", "reliance", "mall of travancore"]',
        '["Amazon shopping", "Lulu supermarket", "Bazaar purchase", "Garment purchase"]',
        17,
        "Debit expenses related to groceries and shopping.",
    ),
    (
        "GR18",
        "Debit tax and government payments",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Tax and Govt Payments",
        '["kerala mission", "9539056194@upi/tax", "tax", "tax/upi"]',
        '["Kerala Mission Tax", "UPI Tax Payment"]',
        18,
        "Debit all expenses related to tax and government charges.",
    ),
    (
        "GR19",
        "Debit groceries and shopping expenses",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Groceries and Shopping",
        '["amazon india", "amazon pay", "amazon seller", "amazonupi", "amznplpvrv", "bazaar pvt lt", "crossword", "lulu", "garments", "lulu international", "lulutrivandrum", "margin free", "pos", "pos atm purch", "pothys", "premier office", "ramachandran", "relia...", "vinu vijayan", "vinu vijayan/upi", "/shambukumar", "more", "more.61839497@", "more.61839878@", "moreretail", "prasanth nagar trivandrum 31", "mall of travancore"]',
        '["Amazon shopping", "Lulu supermarket", "Bazaar purchase", "Garment purchase"]',
        19,
        "Debit expenses related to groceries and shopping.",
    ),
    (
        "GR20",
        "Debit apartment maintenance",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Apartment Maintenance",
        '["sun home", "sunmedanta", "sunmedanta apartment ownersa", "city plaza", "331114505882", "boban george/upi", "c m harshan/upi", "city plaza flat owners asso"]',
        '["Apartment maintenance charges"]',
        20,
        "Debit expenses related to apartment maintenance.",
    ),
    (
        "GR21",
        "Debit medical and pharmacy transfers",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Medical and Pharmacy Transfers",
        '["janasevana kendram", "kottackal arya vaidyasala", "medicals", "pharmacy", "royal kallambalam clinic", "royalkallambalamclinic", "vasudeva vilasam", "g g hospital", "vasan health care", "precise"]',
        '["Pharmacy and Medical transfers"]',
        21,
        "Debit transfers related to medical and pharmacy.",
    ),
    (
        "GR22",
        "Debit entertainment expenses - Inox and PVR",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Entertainment - Inox and PVR",
        '["inox", "INOX", "pvr inox", "pvr limited", "pvrcinemas", "pvrcinemasoffline", "pvrinox831352", "pvrinoxlimited", "bigtree entertainment", "bookmyshow"]',
        '["Entertainment payments for Inox and PVR"]',
        22,
        "Debit entertainment expenses related to Inox and PVR cinema payments.",
    ),
    (
        "GR23",
        "Debit food and dining expenses",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Food and Dining",
        '["bakery", "bhavan", "biryani", "cafe", "cake world", "chothys hospitality", "foods", "fruit juices", "hi tea", "hotel", "master chef", "mc donalds", "restaurant", "taco bell", "vegeatz", "oidztdupic", "payzomato", "zomato", "zomato1paytm", "zomatoonlineorder", "zomatoonlineorder.rzp", "zomato-order for restaurant", "swiggy", "swiggy1online", "swiggyinstamar", "swiggystores", "swiggyupi", "upiswiggy"]',
        '["Food and dining expenses including restaurants, cafes, online orders, and Swiggy"]',
        23,
        "Debit expenses related to food, dining, cafes, restaurants, food delivery services including Swiggy.",
    ),
    (
        "GR24",
        "Debit personal payments to Sumee",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Personal Payments",
        '["9446040282@upi", "Sumee", "sumee"]',
        '["Payments to Sumee"]',
        24,
        "Debit personal payments made to Sumee.",
    ),
    (
        "GR25",
        "Debit car maintenance expenses",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Car Maintenance",
        '["Policy-Bazar", "royal tyre club"]',
        '["Car maintenance payments"]',
        25,
        "Debit expenses related to car maintenance.",
    ),
    (
        "GR26",
        "Debit parking fees",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Car Parking Fees",
        '["parking booth", "parkingbooth"]',
        '["Car parking fees"]',
        26,
        "Debit transfers related to car parking fees.",
    ),
    (
        "GR27",
        "Credit loan given",
        "Nominal",
        "None",
        "Income",
        "Credit",
        "Income",
        "Loan Given",
        '["barat", "barat k gopinath", "baratkgopinath1998", "redteam hacker academy", "gkinter2000-1@", "Gopinath", "beena thingal", "ms. beena thingal"]',
        '["Loan given to others"]',
        27,
        "Credit transfers related to loans given.",
    ),
    (
        "GR28",
        "Debit monthly medicine parents",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Monthly Medicine Parents",
        '["0067015271014", "67015271014", "ajith ghosh m s", "mr. suseelan kunjuram", "suseelan kunjuram"]',
        '["Monthly medicine for mom and dad"]',
        28,
        "Debit transfers related to monthly medicine for parents.",
    ),
    (
        "GR29",
        "Debit personal expenses",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Personal Expenses Mohanan P",
        '["mohanan p", "mohanan p/upi", "mohanan.p.kkm", "haleelulla j", "costa"]',
        '["Personal expenses of Mohanan P"]',
        29,
        "Debit transfers related to personal expenses of Mohanan P.",
    ),
    (
        "GR30",
        "Debit fixed deposit investment",
        "Nominal",
        "None",
        "Investment",
        "Debit",
        "Investment",
        "Fixed Deposit Investment",
        '["0043438795987", "0043438814720", "dr. tran for funding"]',
        '["Fixed deposit investment transactions"]',
        30,
        "Debit transfers related to fixed deposit investments.",
    ),
    (
        "GR31",
        "Debit UPI digital wallet expenses",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "UPI Digital Wallet Expenses",
        '["UPI/airp", "UPIOUT"]',
        '["Digital wallet UPI expenses"]',
        31,
        "Debit expenses made through UPI digital wallets.",
    ),
    (
        "GR32",
        "Debit USD cash withdrawals",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "USD Transfers",
        '["cash wdl usd"]',
        '["USD transfer or cash withdrawal"]',
        32,
        "Cash withdrawals or transfers in USD currency.",
    ),
    (
        "GR33",
        "Debit UPI self transfers",
        "Nominal",
        "None",
        "Transfer",
        "Debit",
        "Transfer",
        "UPI Self Transfers",
        '["9539056194@upi", "sbin123186822129"]',
        '["Self transfer via UPI or digital wallet"]',
        33,
        "Fund movement between own accounts using UPI.",
    ),
    (
        "GR34",
        "Debit home hardware purchases",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Home Hardware Purchases",
        '["3g mobile", "amba store", "electricals"]',
        '["Hardware and electrical items for home maintenance"]',
        34,
        "Debit expenses related to home hardware or electricals.",
    ),
    (
        "GR35",
        "Debit loan repayment",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Loan Repayment",
        '["baiju  suseelan", "loan repayment", "payoff loan", "loan repaid"]',
        '["Loan repayment and payoff"]',
        35,
        "Debit expenses related to repaying personal or external loans.",
    ),
    (
        "GR36",
        "Debit mobile phone recharge",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Mobile Phone Recharge",
        '["vodafone", "mobile phone recharge"]',
        '["Mobile recharge and prepaid payments"]',
        36,
        "Debit expenses related to mobile phone prepaid recharge and payments.",
    ),
    (
        "GR37",
        "Debit suspense account",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Suspense Account",
        '["0042318524988", "0042318738037", "43438814720", "99506044303", "322199330305", "sbin123044482258", "sbin422256210622", "98047706316", "sbin3242273821520097162044301", "sbin1242138970100097942044308"]',
        '["Uncategorized suspense transactions"]',
        37,
        "Debit entries that are unclear or pending classification in suspense account.",
    ),
    (
        "GR38",
        "Debit mutual funds transfers",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Mutual Funds Transfers",
        '["nach"]',
        '["Mutual funds and SIP transfers"]',
        38,
        "Debit transfers related to mutual fund investments and SIPs.",
    ),
    (
        "GR39",
        "Debit cooking gas",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Cooking Gas",
        '["gas", "sudheer", "sudheer  sasidharan"]',
        '["Cooking gas expenses"]',
        39,
        "Debit transfers related to cooking gas expenses.",
    ),
    (
        "GR40",
        "Debit monthly budget",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Monthly Budget",
        '["monthly budget"]',
        '["Monthly budget allocations"]',
        40,
        "Debit transfers related to monthly budget planning.",
    ),
    (
        "GR41",
        "Debit BDS company transactions",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "BDS Company Transactions",
        '["indiafilings pvt ltd", "godaddy"]',
        '["BDS company financial transactions"]',
        41,
        "Debit transfers related to BDS company transactions.",
    ),
    (
        "GR42",
        "Debit CSC company transactions",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "CSC Company Transactions",
        '["csc e governance india limit", "CSC"]',
        '["CSC company financial transactions"]',
        42,
        "Debit transfers related to CSC company transactions.",
    ),
    (
        "GR43",
        "Debit ATM cash withdrawals",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "ATM Cash Withdrawals",
        '["atm cash withdrawal", "atm withdrawal", "cash wdl atm", "atm wdl"]',
        '["ATM cash withdrawal transactions"]',
        43,
        "Debit transfers for ATM cash withdrawals.",
    ),
    (
        "GR44",
        "Credit fund reverse transfers",
        "Nominal",
        "None",
        "Income",
        "Credit",
        "Income",
        "Fund Reverse Transfers",
        '["tfr:wrong entry chq 334293", "fund reverse transfer", "wrong entry chq", "chq 334293 fund reverse"]',
        '["Reversal of wrong fund transfer entries"]',
        44,
        "Credit entries reversing wrong fund transfers or cheque errors.",
    ),
    (
        "GR45",
        "Debit lawyer fees",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Lawyer Fees",
        '["advvsvk@", "lawqua", "vineeth kumar", "vineeth kumar v", "alfaslegal@"]',
        '["Legal and lawyer fees payments"]',
        45,
        "Debit transfers related to lawyer fees and legal services.",
    ),
    (
        "GR46",
        "Credit shares and bonds investment",
        "Nominal",
        "None",
        "Investment",
        "Credit",
        "Investment",
        "Shares and Bonds",
        '["BULK POSTING-ACHCr", "BULK POSTING-SBIMF", "nach_cr"]',
        '["Shares, mutual funds, and bonds investments"]',
        46,
        "Credit transactions related to shares, mutual funds, and bonds investments.",
    ),
    (
        "GR47",
        "Debit self transfer",
        "Nominal",
        "None",
        "Self Transfer",
        "Debit",
        "Self Transfer",
        "Own Account Transfers",
        '["baiju suseelan", "baiju suseelan nair", "baiju suseelan nair/upi", "baiju.s.nair-outlook.com", "baijususeelannair", "baijususeelannair@upi", "direct dr", "mr. baiju  suseelan", "mr. baiju  suseelan", "mob/friends/baiju suseelan nair/", "mob/own account/baiju suseelan nair/"]',
        '["Own account self transfer transactions"]',
        47,
        "Debit transfers related to own account self transfers.",
    ),
    (
        "GR08B",
        "Debit charity and UPI donations",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Charity",
        '["charity", "donation", "upi", "42321673786", "42321674532", "42380688363", "42380692084", "67091477682", "67374881869", "Charity to NGO", "UPI donation reference"]',
        '["Charity to NGO", "UPI donation"]',
        9,
        "Debit all expenses and losses, including digital and charity donations.",
    ),
    (
        "GR49",
        "Debit cash withdrawal transfers",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Cash Withdrawal Transfers",
        '["atm cash", "cash withdrawal", "atm", " 3697 temple view offsite"]',
        '["Cash Withdrawal"]',
        49,
        "Debit transfers related to cash withdrawal from ATM.",
    ),
    (
        "GR50",
        "Fixed Deposit closure transfers",
        "Nominal",
        "None",
        "Income",
        "Credit",
        "Income",
        "Fixed Deposit Closure Transfers",
        '["closure proceeds", "dep tfrfor personal use", "21782300003173", "21782400000236", "21782400000244", "21782400000251", "21782400000699"]',
        '["Fixed Deposit Closed"]',
        50,
        "Credit transfers related to fixed deposit closure proceeds.",
    ),
    (
        "GR51",
        "Fixed Deposit income transfers",
        "Nominal",
        "None",
        "Income",
        "Credit",
        "Income",
        "Fixed Deposit Income Transfers",
        '["21782400000269", "21782400000277", "21782400000285", "21782400000699", "21782400000707", "21782400000715"]',
        '["Fixed Deposit Income"]',
        51,
        "Credit transfers related to fixed deposit income.",
    ),
    (
        "GR52",
        "Rent Income",
        "Nominal",
        "None",
        "Income",
        "Credit",
        "Income",
        "Rent Income",
        '["neenu joseph"]',
        '["Rent Income"]',
        52,
        "Rent received from tenants.",
    ),
    (
        "GR53",
        "Locker Rent Expense",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Locker Rent",
        '["loan repay", "locker rent", "locker charges", "wdl tfr locker rent"]',
        '["Locker Rent Expense"]',
        53,
        "Expenses related to locker rent and charges.",
    ),
    (
        "GR54",
        "Locker Rent Refund",
        "Nominal",
        "None",
        "Income",
        "Credit",
        "Income",
        "Locker Rent Refund",
        '["locker excess rent", "locker rent refund", "locker rent reversed"]',
        '["Locker Rent Refund"]',
        54,
        "Refund or reversal of locker rent charges.",
    ),
    (
        "GR55",
        "Debit Mutual Fund Transactions",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Mutual Fund Transactions",
        '["debit-cmp", "mutual fund debit", "mf debit"]',
        '["Mutual Fund Payments"]',
        55,
        "Debit transactions related to mutual fund investments.",
    ),
    (
        "GR56",
        "Mutual Fund and ULIP Surrender Income",
        "Nominal",
        "None",
        "Income",
        "Credit",
        "Income",
        "ULIP surrender and mutual fund redemption",
        '["ulip surrender", "mutual fund surrendered", "mf redemption", "ulip redemption", "investment intermediar", "dep tfr cmb sbi"]',
        '["Mutual Fund and ULIP Surrender Income"]',
        56,
        "Income from ULIP surrender or mutual fund redemption.",
    ),
    (
        "GR57",
        "Fund Reversal Entries",
        "Nominal",
        "None",
        "Income",
        "Credit",
        "Income",
        "Fund Reversals",
        '["reverse", "reversed", "reversal", "fund reversed", "reversed entry"]',
        '["Fund Reversal Income"]',
        57,
        "Fund reversed back to account, treated as income correction.",
    ),
    (
        "GR58",
        "Cash/Cheque Withdrawals",
        "Nominal",
        "None",
        "Asset",
        "Debit",
        "Asset",
        "Cash Withdrawals",
        '["cas cash", "cas chq", "cash chq", "cash cheque"]',
        '["Cash Withdrawal"]',
        58,
        "Cash or cheque withdrawal transactions.",
    ),
    (
        "GR59",
        "Cash Deposit by Beena",
        "Nominal",
        "None",
        "Asset",
        "Credit",
        "Asset",
        "Cash Deposits",
        '["cash deposit beena", "cash deposit by beena", "beena cash deposit"]',
        '["Cash Deposit"]',
        59,
        "Cash deposited into the account by Beena's family.",
    ),
    (
        "GR60",
        "Fixed Deposit Investment",
        "Nominal",
        "None",
        "Asset",
        "Debit",
        "Asset",
        "Fixed Deposit",
        '["21782300003181", "21782400000269"]',
        '["Fixed Deposit"]',
        60,
        "Investment made as Fixed Deposit.",
    ),
    (
        "GR61",
        "Media Subscriptions",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Media & Subscriptions",
        '["google", "apple", "apple media", "google media", "google subscription", "apple subscription", "microsoft", "microsoft subscription", "ms 365"]',
        '["Media Subscriptions"]',
        61,
        "Payments made to Google and Apple for media subscriptions.",
    ),
    (
        "GR62",
        "Insurance Payment",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Insurance",
        '["neft:lic", "lic premium", "insurance payment"]',
        '["LIC", "Life Insurance", "Insurance Premium"]',
        62,
        "Payments made towards insurance policies like LIC or other premium deductions.",
    ),
    (
        "GR64",
        "Sun Homes Apartment Purchase",
        "Capital",
        "None",
        "Asset",
        "Debit",
        "Asset",
        "Real Estate",
        '["67053179635", "sun homes", "sunhomes", "flat purchase"]',
        '["apartment", "flat", "real estate", "property purchase"]',
        64,
        "Capital investment for purchasing a Sun Homes apartment. Treated as a real estate asset.",
    ),
    (
        "GR65",
        "Railway Transportation and IRCTC",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Railway and IRCTC Expenses",
        '["irctc", "railway", "rail transport", "train tickets"]',
        '["transportation", "railway"]',
        65,
        "Expenses related to railway transportation and IRCTC bookings.",
    ),
    (
        "GR66",
        "UPI Digital Wallet Incoming Funds",
        "Nominal",
        "None",
        "Income",
        "Credit",
        "Income",
        "UPI wallet incoming transfers",
        '["upi in", "upi in/", "upirev", "sumee s", "upi"]',
        '["Digital Wallet Incoming"]',
        66,
        "Funds received via UPI digital wallets.",
    ),
    (
        "GR67",
        "UPI Digital Wallet Expense",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Payments via UPI digital wallets",
        '["upi/", "upi/fdrl"]',
        '["Digital Wallet Expense"]',
        67,
        "Payments made via UPI digital wallets.",
    ),
    (
        "GR68",
        "Fund Transfer to Friends",
        "Nominal",
        "None",
        "Expense",
        "Debit",
        "Expense",
        "Fund transfers to friends",
        '["neft:mr sundaresan sujith"]',
        '["Fund Transfer to Friends"]',
        68,
        "Fund transferred to friends via NEFT.",
    ),
    (
        "GR69",
        "Salary and EOSB",
        "Nominal",
        "None",
        "Income",
        "Credit",
        "Income",
        "Salary and End of Service Benefits",
        '["qpay sbin322249093092"]',
        '["Salary and EOSB"]',
        69,
        "Monthly salary and EOSB credited via QPAY.",
    ),
    (
        "GR70",
        "Bank Transfer",
        "Nominal",
        "None",
        "Transfer",
        "Debit",
        "Transfer",
        "Bank transfer expenses",
        '["dep tfr"]',
        '["dep tfr"]',
        70,
        "Funds transferred via bank transfer (dep tfr).",
    ),
    (
        "GR71",
        "Self Bank to Bank Transfer",
        "Nominal",
        "None",
        "Transfer",
        "Debit",
        "Transfer",
        "Self bank-to-bank transfer",
        '["sbinr52023070559034557", "/baiju suseelan nair/moblta"]',
        '["Self Bank Transfer"]',
        71,
        "Self transfer from SBI to FED bank.",
    ),
    (
        "GR73",
        "Self Bank Transfer to SBI Account 67093359418",
        "Nominal",
        "None",
        "Transfer",
        "Debit",
        "Transfer",
        "Self bank-to-bank transfer",
        '["transfer to 67093359418"]',
        '["Self Bank Transfer"]',
        73,
        "Self bank transfer to SBI account 67093359418.",
    ),
    (
        "GR74",
        "Self Transfer to SBI Account",
        "Nominal",
        "None",
        "Transfer",
        "Debit",
        "Transfer",
        "Self bank-to-bank transfer",
        '["xx0049", "XX0049/Pay to acc", "049sibl", "060sibl", "/sibl-xx081", "081sibl", "sibl-xx081"]',
        '["Self Transfer to SBI"]',
        74,
        "Transfer to own SBI account with reference XX0049.",
    ),
    (
        "GR75",
        "IMPS Fund Transfer from SIB",
        "Nominal",
        "None",
        "Transfer",
        "Debit",
        "Transfer",
        "IMPS fund transfer from SIB",
        '["wdl tfr  inb imps"]',
        '["IMPS Transfer from SIB"]',
        75,
        "Fund transfer via IMPS from SIB account.",
    ),
]


def seed_compact_rules():
    print("⏳ Running rulebook compaction and database injection run...")

    with transaction.atomic():
        created_count = 0
        for row in RAW_RULES_EXPORT:
            # Safely serialize standard array string payloads
            tags = json.loads(row[8])
            examples = json.loads(row[9])

            # Pack all descriptive metadata paths straight into the JSON configuration vault block
            compacted_metadata = {
                "golden_rule_type": row[2],
                "account_type": row[3],
                "golden_rule_summary": row[11],
                "category": row[6],
                "subcategory": row[7],
            }

            obj, created = AccountingRule.objects.update_or_create(
                rule_code=row[0],
                defaults={
                    "rule_title": row[1],
                    "entry_type": row[5],
                    "rule_priority": int(row[10]),
                    "description_tags": tags,
                    "examples": examples,
                    "rule_metadata": compacted_metadata,
                    "is_active": True,
                    "apply_to_ai": False,
                },
            )
            if created:
                created_count += 1

        print(
            f"🎉 Compaction sync complete! {created_count} rules loaded successfully."
        )


if __name__ == "__main__":
    seed_compact_rules()
