import os
import sys
import json
import logging
import django

# 1. Point Python to your project root and set Django Settings
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "core.settings")

# 2. Initialize Django BEFORE importing models
django.setup()

# 3. Model imports (MUST come after django.setup())
from django.db import transaction
from tracker.models import AccountingRule

logger = logging.getLogger(__name__)

GOLDEN_RULES_DATA = [
    # =========================================================================
    # 1. PERSONAL ACCOUNTS (DEBIT RECEIVER / CREDIT GIVER)
    # =========================================================================
    {
        "id": 1,
        "rule_code": "GR01",
        "rule_title": "Debit the receiver",
        "entry_type": "Debit",
        "rule_priority": 1,
        "description_tags": ["receiver", "given", "receive"],
        "examples": ["Received cash", "Payment received"],
        "rule_metadata": {
            "category": "Asset",
            "subcategory": "Personal Receivables",
            "account_type": "None",
            "golden_rule_type": "Personal",
            "golden_rule_summary": "When a person receives value, debit their account.",
        },
    },
    {
        "id": 2,
        "rule_code": "GR02",
        "rule_title": "Credit the giver",
        "entry_type": "Credit",
        "rule_priority": 2,
        "description_tags": ["giver", "given", "payment"],
        "examples": ["Paid cash", "Payment made"],
        "rule_metadata": {
            "category": "Liability",
            "subcategory": "Personal Payables",
            "account_type": "None",
            "golden_rule_type": "Personal",
            "golden_rule_summary": "When a person gives value, credit their account.",
        },
    },
    {
        "id": 27,
        "rule_code": "GR27",
        "rule_title": "Credit loan given / personal receivables",
        "entry_type": "Credit",
        "rule_priority": 27,
        "description_tags": [
            "barat",
            "barat k gopinath",
            "baratkgopinath1998",
            "redteam hacker academy",
            "gkinter2000-1@",
            "Gopinath",
            "beena thingal",
            "ms. beena thingal",
        ],
        "examples": ["Loan given to others"],
        "rule_metadata": {
            "category": "Asset",
            "subcategory": "Loans & Receivables",
            "account_type": "None",
            "golden_rule_type": "Personal",
            "golden_rule_summary": "Credit transfers related to loans given or recovered.",
        },
    },
    {
        "id": 35,
        "rule_code": "GR35",
        "rule_title": "Debit loan repayment",
        "entry_type": "Debit",
        "rule_priority": 35,
        "description_tags": [
            "loan repayment",
            "payoff loan",
            "loan repaid",
        ],
        "examples": ["Loan repayment and payoff"],
        "rule_metadata": {
            "category": "Liability",
            "subcategory": "Loans & Repayments",
            "account_type": "None",
            "golden_rule_type": "Personal",
            "golden_rule_summary": "Loan account principal/interest payments.",
        },
    },
    # =========================================================================
    # 2. REAL ACCOUNTS (DEBIT WHAT COMES IN / CREDIT WHAT GOES OUT)
    # =========================================================================
    {
        "id": 3,
        "rule_code": "GR03",
        "rule_title": "Debit what comes in (Real Assets)",
        "entry_type": "Debit",
        "rule_priority": 3,
        "description_tags": ["purchase", "bought", "received"],
        "examples": ["Bought equipment", "Received goods"],
        "rule_metadata": {
            "category": "Asset",
            "subcategory": "Real Assets",
            "account_type": "None",
            "golden_rule_type": "Real",
            "golden_rule_summary": "Debit the asset that comes into the business.",
        },
    },
    {
        "id": 4,
        "rule_code": "GR04",
        "rule_title": "Credit what goes out (Real Assets)",
        "entry_type": "Credit",
        "rule_priority": 4,
        "description_tags": ["sold", "disposed"],
        "examples": ["Sold equipment", "Goods disposed"],
        "rule_metadata": {
            "category": "Asset",
            "subcategory": "Real Assets",
            "account_type": "None",
            "golden_rule_type": "Real",
            "golden_rule_summary": "Credit the asset when it goes out of the business.",
        },
    },
    {
        "id": 9,
        "rule_code": "GR09",
        "rule_title": "Debit gold purchase and jewellery",
        "entry_type": "Debit",
        "rule_priority": 9,
        "description_tags": [
            "bhima",
            "bhima jewellers and diamonds",
            "bhima jewellery",
            "joyalukkas",
            "kalyan",
        ],
        "examples": ["Bhima jewellers purchase", "Gold purchase at Joyalukkas"],
        "rule_metadata": {
            "category": "Asset",
            "subcategory": "Gold & Precious Metals",
            "account_type": "None",
            "golden_rule_type": "Real",
            "golden_rule_summary": "Debit asset value for gold and jewellery purchases.",
        },
    },
    {
        "id": 10,
        "rule_code": "GR10",
        "rule_title": "Investment in Life Insurance",
        "entry_type": "Debit",
        "rule_priority": 10,
        "description_tags": [
            "ageasfddc",
            "sbi-life",
            "sbi life insurance",
            "hdfc-life",
            "sbin2250080903300097160044302",
        ],
        "examples": ["SBI Life insurance premium", "Investment in SBI Life"],
        "rule_metadata": {
            "category": "Asset",
            "subcategory": "Insurance Assets",
            "account_type": "None",
            "golden_rule_type": "Real",
            "golden_rule_summary": "Debit asset account for investments in life insurance policies.",
        },
    },
    {
        "id": 15,
        "rule_code": "GR15",
        "rule_title": "Investment in Health Insurance",
        "entry_type": "Debit",
        "rule_priority": 15,
        "description_tags": ["arogya policy", "health insurance", "health policy"],
        "examples": ["Arogya health insurance premium"],
        "rule_metadata": {
            "category": "Asset",
            "subcategory": "Insurance Assets",
            "account_type": "None",
            "golden_rule_type": "Real",
            "golden_rule_summary": "Debit asset account for investments in health insurance policies.",
        },
    },
    {
        "id": 16,
        "rule_code": "GR16",
        "rule_title": "Investment in Pension Scheme",
        "entry_type": "Debit",
        "rule_priority": 16,
        "description_tags": ["national pension scheme", "nps cams", "nps"],
        "examples": ["NPS contribution", "NPS CAMS payment"],
        "rule_metadata": {
            "category": "Asset",
            "subcategory": "Pension & Retirement",
            "account_type": "None",
            "golden_rule_type": "Real",
            "golden_rule_summary": "Debit asset account for investments in pension schemes.",
        },
    },
    {
        "id": 30,
        "rule_code": "GR30",
        "rule_title": "Debit fixed deposit investment",
        "entry_type": "Debit",
        "rule_priority": 30,
        "description_tags": [
            "0043438795987",
            "0043438814720",
            "dr. tran for funding",
            "21782300003181",
            "21782400000269",
        ],
        "examples": ["Fixed deposit investment transactions"],
        "rule_metadata": {
            "category": "Asset",
            "subcategory": "Fixed Deposits",
            "account_type": "None",
            "golden_rule_type": "Real",
            "golden_rule_summary": "Debit investments made into fixed deposit accounts.",
        },
    },
    {
        "id": 63,
        "rule_code": "GR64",
        "rule_title": "Real Estate & Property Purchase",
        "entry_type": "Debit",
        "rule_priority": 64,
        "description_tags": [
            "67053179635",
            "sun homes",
            "sunhomes",
            "flat purchase",
            "apartment",
            "flat",
            "real estate",
            "property purchase",
        ],
        "examples": ["Sun Homes flat purchase"],
        "rule_metadata": {
            "category": "Asset",
            "subcategory": "Real Estate",
            "account_type": "None",
            "golden_rule_type": "Real",
            "golden_rule_summary": "Capital investment for purchasing real estate property.",
        },
    },
    {
        "id": 76,
        "rule_code": "GR77",
        "rule_title": "Debit ShareMarket & Investment Allocation",
        "entry_type": "Debit",
        "rule_priority": 77,
        "description_tags": [
            "BULK POSTING-ACHCr",
            "BULK POSTING-SBIMF",
            "nach cr",
            "share",
            "trading",
            "geojit",
            "caps",
            "ipo",
        ],
        "examples": ["Share and mutual fund purchases"],
        "rule_metadata": {
            "category": "Asset",
            "subcategory": "ShareMarket & Mutual Funds",
            "account_type": "None",
            "golden_rule_type": "Real",
            "golden_rule_summary": "Debit asset account for share market, equity, and mutual fund acquisitions.",
        },
    },
    # =========================================================================
    # 3. NOMINAL ACCOUNTS (DEBIT EXPENSES & LOSSES)
    # =========================================================================
    {
        "id": 5,
        "rule_code": "GR05",
        "rule_title": "Debit all expenses and losses",
        "entry_type": "Debit",
        "rule_priority": 5,
        "description_tags": ["expense", "loss", "cost"],
        "examples": ["Electricity bill", "Repair cost"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "General Operating Expenses",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Debit all baseline expenses and operational losses.",
        },
    },
    {
        "id": 7,
        "rule_code": "GR07",
        "rule_title": "Debit bank charges and fees",
        "entry_type": "Debit",
        "rule_priority": 7,
        "description_tags": [
            "bank charge",
            "fail chrg",
            "debit mandate",
            "fee",
            "maint",
            "sms",
            "service",
            "amc",
            "cash wdl service",
            "charges for rtgs",
            "chrg",
            "chrg/imps",
            "chrg/min bal",
            "commission",
            "debit card amc",
            "imps charges",
            "insufficient bal",
            "mandate fail chrg",
            "min bal",
            "minimum balance charges",
            "sms charges",
            "wdl service",
            "wdlservice",
        ],
        "examples": ["SMS alert fee", "Bank maintenance charge"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Bank Charges & Fees",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Debit bank service charges, penalty fees, and processing charges.",
        },
    },
    {
        "id": 8,
        "rule_code": "GR08A",
        "rule_title": "Debit temple and religious donations",
        "entry_type": "Debit",
        "rule_priority": 8,
        "description_tags": [
            "mandir",
            "church",
            "mosque",
            "religious",
            "mukalvata",
            "sree padmanabhaswamy",
            "temple donation",
            "religious offering",
            "mukalvata payment",
            "sree panchami devi temple",
            "travancore devaswom board",
            "devasam",
            "charity",
            "donation",
        ],
        "examples": ["Temple donation", "Charity to NGO"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Donations & Religious",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Debit expenses related to religious offerings, temple donations, and charity.",
        },
    },
    {
        "id": 11,
        "rule_code": "GR11",
        "rule_title": "Debit utility and bill payments",
        "entry_type": "Debit",
        "rule_priority": 11,
        "description_tags": [
            "airtel",
            "disney hotsta",
            "air fiber",
            "jio",
            "government of kerala bill",
            "kerala state electricity",
            "kseb",
            "kerala state road transport",
            "ksstm",
            "kwat",
            "water bill",
            "electricity",
            "internet bill",
        ],
        "examples": ["Airtel mobile payment", "Kerala electricity bill"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Utilities & Bills",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Debit utility expenses including electricity, water, internet, and mobile.",
        },
    },
    {
        "id": 12,
        "rule_code": "GR12",
        "rule_title": "Debit entertainment expenses",
        "entry_type": "Debit",
        "rule_priority": 12,
        "description_tags": [
            "amazon prime",
            "disney hotstar",
            "streaming",
            "subscription",
            "netflix",
            "inox",
            "pvr inox",
            "pvr limited",
            "pvrcinemas",
            "pvrcinemasoffline",
            "pvrinox831352",
            "pvrinoxlimited",
            "bigtree entertainment",
            "bookmyshow",
        ],
        "examples": ["Amazon Prime subscription", "PVR ticket payment"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Entertainment & Media",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Debit entertainment, cinema, and media streaming subscriptions.",
        },
    },
    {
        "id": 13,
        "rule_code": "GR13",
        "rule_title": "Debit education and trust fees",
        "entry_type": "Debit",
        "rule_priority": 13,
        "description_tags": [
            "jain trust",
            "jain university",
            "jainonline",
            "jainuniversi",
        ],
        "examples": ["Jain University fees"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Education & Trust Fees",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Debit educational tuition fees and trust payments.",
        },
    },
    {
        "id": 14,
        "rule_code": "GR14",
        "rule_title": "Debit fuel and transport expenses",
        "entry_type": "Debit",
        "rule_priority": 14,
        "description_tags": [
            "fuel",
            "petrol",
            "diesel",
            "gasoline",
            "transport",
            "vehicle",
            "bharat petroleum",
            "indian oil",
            "shell",
            "hindustan petroleum",
            "hpcl",
            "iocl",
            "bunk",
            "petrolpump",
            "nagarajan and sons",
            "nagarajan s",
            "irctc",
            "railway",
            "rail transport",
            "train tickets",
        ],
        "examples": ["Fuel for vehicle", "IRCTC train ticket"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Fuel & Transport",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Debit fuel, petrol, railway bookings, and vehicle transport charges.",
        },
    },
    {
        "id": 17,
        "rule_code": "GR17",
        "rule_title": "Debit groceries and shopping expenses",
        "entry_type": "Debit",
        "rule_priority": 17,
        "description_tags": [
            "amazon india",
            "amazon pay",
            "amazon seller",
            "amazonupi",
            "amznplpvrv",
            "bazaar pvt lt",
            "crossword",
            "lulu",
            "garments",
            "lulu international",
            "lulutrivandrum",
            "margin free",
            "pos",
            "pos atm purch",
            "pothys",
            "premier office",
            "ramachandran",
            "reliance",
            "mall of travancore",
            "vinu vijayan",
            "more",
            "moreretail",
            "prasanth nagar trivandrum 31",
        ],
        "examples": ["Amazon shopping", "Lulu supermarket purchase"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Groceries & Shopping",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Debit retail shopping, supermarket purchases, and apparel expenses.",
        },
    },
    {
        "id": 18,
        "rule_code": "GR18",
        "rule_title": "Debit tax and government payments",
        "entry_type": "Debit",
        "rule_priority": 18,
        "description_tags": ["kerala mission", "9539056194@upi/tax", "tax", "tax/upi"],
        "examples": ["Kerala Mission Tax payment"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Tax & Government Fees",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Debit tax assessments, government duties, and official fees.",
        },
    },
    {
        "id": 20,
        "rule_code": "GR20",
        "rule_title": "Debit apartment maintenance",
        "entry_type": "Debit",
        "rule_priority": 20,
        "description_tags": [
            "sun home",
            "sunmedanta",
            "sunmedanta apartment ownersa",
            "city plaza",
            "331114505882",
            "boban george/upi",
            "c m harshan/upi",
            "city plaza flat owners asso",
        ],
        "examples": ["Apartment maintenance charges"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Housing & Maintenance",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Debit residential society fees and building maintenance.",
        },
    },
    {
        "id": 21,
        "rule_code": "GR21",
        "rule_title": "Debit medical and pharmacy expenses",
        "entry_type": "Debit",
        "rule_priority": 21,
        "description_tags": [
            "janasevana kendram",
            "kottackal arya vaidyasala",
            "medicals",
            "pharmacy",
            "royal kallambalam clinic",
            "royalkallambalamclinic",
            "vasudeva vilasam",
            "g g hospital",
            "vasan health care",
            "precise",
            "0067015271014",
            "67015271014",
            "ajith ghosh m s",
            "mr. suseelan kunjuram",
            "suseelan kunjuram",
            "janashraya community pharmac",
        ],
        "examples": ["Pharmacy and clinic payments", "Parent monthly medicine"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Medical & Healthcare",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Debit pharmacy, clinical consultation, hospital, and recurring medical costs.",
        },
    },
    {
        "id": 23,
        "rule_code": "GR23",
        "rule_title": "Debit food and dining expenses",
        "entry_type": "Debit",
        "rule_priority": 23,
        "description_tags": [
            "bakery",
            "bhavan",
            "biryani",
            "cafe",
            "cake world",
            "chothys hospitality",
            "foods",
            "fruit juices",
            "hi tea",
            "hotel",
            "master chef",
            "mc donalds",
            "restaurant",
            "taco bell",
            "vegeatz",
            "oidztdupic",
            "payzomato",
            "zomato",
            "zomato1paytm",
            "zomatoonlineorder",
            "zomatoonlineorder.rzp",
        ],
        "examples": ["Restaurant bill", "Zomato order"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Food & Dining",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Debit restaurant dining, cafes, bakeries, and food delivery services.",
        },
    },
    {
        "id": 24,
        "rule_code": "GR24",
        "rule_title": "Debit personal payments to family",
        "entry_type": "Debit",
        "rule_priority": 24,
        "description_tags": ["9446040282@upi", "geetha gopalan"],
        "examples": ["Payments to family members"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Personal & Family",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Debit personal family disbursements and household allocations.",
        },
    },
    {
        "id": 25,
        "rule_code": "GR25",
        "rule_title": "Debit vehicle maintenance & parking",
        "entry_type": "Debit",
        "rule_priority": 25,
        "description_tags": [
            "policy-bazar",
            "royal tyre club",
            "parking booth",
            "parkingbooth",
        ],
        "examples": ["Tyre replacement", "Parking fee"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Vehicle Maintenance & Parking",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Debit vehicle maintenance, tyre replacements, and parking fees.",
        },
    },
    {
        "id": 34,
        "rule_code": "GR34",
        "rule_title": "Debit home hardware & electricals",
        "entry_type": "Debit",
        "rule_priority": 34,
        "description_tags": [
            "3g mobile",
            "amba store",
            "electricals",
            "arun painting",
            "praveen p",
        ],
        "examples": ["Electrical items for maintenance", "Arun painting charges"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Hardware & Home Repairs",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Debit hardware store, painting labor, and home repair costs.",
        },
    },
    {
        "id": 36,
        "rule_code": "GR36",
        "rule_title": "Debit mobile phone recharge",
        "entry_type": "Debit",
        "rule_priority": 36,
        "description_tags": [
            "vodafone",
            "mobile phone recharge",
            "dth rech arge",
            "dth recharge",
            "mobile recharge",
        ],
        "examples": ["Vodafone prepaid recharge", "DTH recharge"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Utilities & Bills",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Debit mobile prepaid recharges and cellular/DTH connections.",
        },
    },
    {
        "id": 39,
        "rule_code": "GR39",
        "rule_title": "Debit cooking gas",
        "entry_type": "Debit",
        "rule_priority": 39,
        "description_tags": ["gas", "sudheer", "sudheer sasidharan"],
        "examples": ["Cooking gas refill"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Utilities & Bills",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Debit LPG cooking gas cylinder refills and supply charges.",
        },
    },
    {
        "id": 41,
        "rule_code": "GR41",
        "rule_title": "Debit professional & corporate software fees",
        "entry_type": "Debit",
        "rule_priority": 41,
        "description_tags": [
            "indiafilings pvt ltd",
            "godaddy",
            "csc e governance india limit",
            "csc",
        ],
        "examples": ["Indiafilings service charge", "GoDaddy domain renewal"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Legal & Professional Services",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Debit professional service charges, filings, web hosting, and corporate tools.",
        },
    },
    {
        "id": 45,
        "rule_code": "GR45",
        "rule_title": "Debit legal & lawyer fees",
        "entry_type": "Debit",
        "rule_priority": 45,
        "description_tags": [
            "advvsvk@",
            "lawqua",
            "vineeth kumar",
            "vineeth kumar v",
            "alfaslegal@",
        ],
        "examples": ["Lawyer professional fees"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Legal & Professional Services",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Debit advocate retainers, court fees, and legal service charges.",
        },
    },
    {
        "id": 53,
        "rule_code": "GR53",
        "rule_title": "Locker Rent & Bank Services",
        "entry_type": "Debit",
        "rule_priority": 53,
        "description_tags": [
            "loan repay",
            "locker rent",
            "locker charges",
            "wdl tfr locker rent",
        ],
        "examples": ["Bank locker rent charge"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Bank Charges & Fees",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Debit bank safe deposit box locker rental charges.",
        },
    },
    {
        "id": 61,
        "rule_code": "GR61",
        "rule_title": "Media & Cloud Subscriptions",
        "entry_type": "Debit",
        "rule_priority": 61,
        "description_tags": [
            "google",
            "apple",
            "apple media",
            "google media",
            "google subscription",
            "apple subscription",
            "microsoft",
            "microsoft subscription",
            "ms 365",
        ],
        "examples": ["Google One subscription", "Microsoft 365 payment"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Entertainment & Media",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Debit cloud storage, app store purchases, and media subscriptions.",
        },
    },
    {
        "id": 62,
        "rule_code": "GR62",
        "rule_title": "LIC & Insurance Premiums",
        "entry_type": "Debit",
        "rule_priority": 62,
        "description_tags": ["neft:lic", "lic premium", "insurance payment"],
        "examples": ["LIC insurance premium"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Insurance Premiums",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Debit regular insurance policy premium payments.",
        },
    },
    # =========================================================================
    # 🎯 NEW TARGETED EXPENSE RULES (HIGH FREQUENCY UNMATCHED PATTERNS)
    # =========================================================================
    {
        "id": 101,
        "rule_code": "GR101",
        "rule_title": "Swiggy Food & Online Delivery",
        "entry_type": "Debit",
        "rule_priority": 101,
        "description_tags": [
            "swiggy",
            "swiggystores",
            "swiggy.stores",
            "swiggy1online",
            "swiggyinstamar",
            "swiggyupi",
            "upiswiggy",
            "swiggy limited",
            "swiggy ltd",
        ],
        "examples": ["Swiggy food order", "Swiggy stores payment"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Food & Dining",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Debit online food delivery and instamart grocery charges via Swiggy.",
        },
    },
    {
        "id": 102,
        "rule_code": "GR102",
        "rule_title": "Bakery, Sweets & Food Outlets",
        "entry_type": "Debit",
        "rule_priority": 102,
        "description_tags": [
            "supreme bakery",
            "supreme bakery and stores",
            "mohanan p",
            "mohanan.p.kkm",
        ],
        "examples": ["Supreme bakery purchase", "Local bakery vendor"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Food & Dining",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Debit food and bakery purchases from registered retail outlets.",
        },
    },
    {
        "id": 103,
        "rule_code": "GR103",
        "rule_title": "Auto & Local Transport",
        "entry_type": "Debit",
        "rule_priority": 103,
        "description_tags": ["roy r/auto", "roy r", "auto fare"],
        "examples": ["Roy auto transport fare"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Fuel & Transport",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Debit auto rickshaw and local short-distance travel fares.",
        },
    },
    # =========================================================================
    # 4. NOMINAL ACCOUNTS (CREDIT INCOMES & GAINS)
    # =========================================================================
    {
        "id": 6,
        "rule_code": "GR06",
        "rule_title": "Credit all incomes and gains",
        "entry_type": "Credit",
        "rule_priority": 6,
        "description_tags": [
            "income",
            "sales",
            "revenue",
            "gain",
            "int on fd inr",
            "interest credit",
            "int trf",
            "sbint",
            "int.pd",
            "43438795987",
        ],
        "examples": ["Sales income", "Bank interest received"],
        "rule_metadata": {
            "category": "Income",
            "subcategory": "Revenue & Gains",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Credit all baseline business revenue, sales, and interest income.",
        },
    },
    {
        "id": 44,
        "rule_code": "GR44",
        "rule_title": "Credit fund reverse & error entries",
        "entry_type": "Credit",
        "rule_priority": 44,
        "description_tags": [
            "tfr:wrong entry chq 334293",
            "fund reverse transfer",
            "wrong entry chq",
            "chq 334293 fund reverse",
            "reverse",
            "reversed",
            "reversal",
            "fund reversed",
            "reversed entry",
        ],
        "examples": ["Reversal of wrong entry", "Cheque error reversal"],
        "rule_metadata": {
            "category": "Income",
            "subcategory": "Refunds & Reversals",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Credit entries reversing erroneous debits or bank charges.",
        },
    },
    {
        "id": 50,
        "rule_code": "GR50",
        "rule_title": "Fixed Deposit closure proceeds",
        "entry_type": "Credit",
        "rule_priority": 50,
        "description_tags": [
            "closure proceeds",
            "dep tfrfor personal use",
            "21782300003173",
            "21782400000236",
            "21782400000244",
            "21782400000251",
            "21782400000699",
            "21782400000269",
            "21782400000277",
            "21782400000285",
            "21782400000707",
            "21782400000715",
        ],
        "examples": ["FD maturity closure proceeds"],
        "rule_metadata": {
            "category": "Income",
            "subcategory": "Investment Returns",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Credit fixed deposit closure proceeds and yield returns.",
        },
    },
    {
        "id": 52,
        "rule_code": "GR52",
        "rule_title": "Rent Income Receipts",
        "entry_type": "Credit",
        "rule_priority": 52,
        "description_tags": ["neenu joseph"],
        "examples": ["Tenant rent credit"],
        "rule_metadata": {
            "category": "Income",
            "subcategory": "Rent Income",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Credit rental income received from tenant properties.",
        },
    },
    {
        "id": 54,
        "rule_code": "GR54",
        "rule_title": "Locker Rent & Fee Refunds",
        "entry_type": "Credit",
        "rule_priority": 54,
        "description_tags": [
            "locker excess rent",
            "locker rent refund",
            "locker rent reversed",
        ],
        "examples": ["Locker fee refund"],
        "rule_metadata": {
            "category": "Income",
            "subcategory": "Refunds & Reversals",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Credit refunds or reversals of bank locker charges.",
        },
    },
    {
        "id": 56,
        "rule_code": "GR56",
        "rule_title": "Mutual Fund & ULIP Redemption Income",
        "entry_type": "Credit",
        "rule_priority": 56,
        "description_tags": [
            "ulip surrender",
            "mutual fund surrendered",
            "mf redemption",
            "ulip redemption",
            "investment intermediar",
            "dep tfr cmb sbi",
        ],
        "examples": ["ULIP redemption credit"],
        "rule_metadata": {
            "category": "Income",
            "subcategory": "Investment Returns",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Credit income from mutual fund redemptions and ULIP policy surrenders.",
        },
    },
    {
        "id": 68,
        "rule_code": "GR69",
        "rule_title": "Salary and EOSB Income",
        "entry_type": "Credit",
        "rule_priority": 69,
        "description_tags": ["qpay sbin322249093092"],
        "examples": ["Monthly salary credit via QPAY"],
        "rule_metadata": {
            "category": "Income",
            "subcategory": "Salary & EOSB",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Credit monthly salary credits and end-of-service employee benefits.",
        },
    },
    {
        "id": 75,
        "rule_code": "GR76",
        "rule_title": "ShareMarket Dividend & Return Inbound",
        "entry_type": "Credit",
        "rule_priority": 76,
        "description_tags": [
            "BULK POSTING-ACHCr",
            "BULK POSTING-SBIMF",
            "nach cr",
            "share",
            "trading",
            "geojit",
            "caps",
            "ipo",
            "hcl technologies",
        ],
        "examples": ["Dividend yield credit"],
        "rule_metadata": {
            "category": "Income",
            "subcategory": "Investment Returns",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Credit dividends, capital gains returns, and market investment payouts.",
        },
    },
    {
        "id": 79,
        "rule_code": "GR78_CR",
        "rule_title": "Interest Income Receipts",
        "entry_type": "Credit",
        "rule_priority": 78,
        "description_tags": ["intcr", "sbint", "interest"],
        "examples": ["Savings account interest credit"],
        "rule_metadata": {
            "category": "Income",
            "subcategory": "Interest Income",
            "account_type": "None",
            "golden_rule_type": "Nominal",
            "golden_rule_summary": "Credit interest earnings paid by banking institutions.",
        },
    },
    # =========================================================================
    # 5. INTER-ACCOUNT CONTRA & INTERNAL TRANSFERS (TIER 2 / LIQUIDITY)
    # =========================================================================
    {
        "id": 33,
        "rule_code": "GR33",
        "rule_title": "Debit UPI & Wallet Self Transfers",
        "entry_type": "Debit",
        "rule_priority": 33,
        "description_tags": [
            "9539056194@upi",
            "sbin123186822129",
            "upi/airp",
            "upiout",
        ],
        "examples": ["UPI digital wallet outflow"],
        "rule_metadata": {
            "category": "Transfer",
            "subcategory": "Self Inter-Account",
            "account_type": "None",
            "golden_rule_type": "Personal",
            "golden_rule_summary": "Fund movement between personal accounts via digital wallets.",
        },
    },
    {
        "id": 43,
        "rule_code": "GR43",
        "rule_title": "Debit ATM & Cash Withdrawals",
        "entry_type": "Debit",
        "rule_priority": 43,
        "description_tags": [
            "atm cash withdrawal",
            "atm withdrawal",
            "cash wdl atm",
            "atm wdl",
            "atm cash",
            "cash withdrawal",
            "atm",
            "3697 temple view offsite",
            "cas cash",
            "cas chq",
            "cash chq",
            "cash cheque",
        ],
        "examples": ["ATM cash withdrawal"],
        "rule_metadata": {
            "category": "Transfer",
            "subcategory": "ATM & Cash Withdrawals",
            "account_type": "None",
            "golden_rule_type": "Personal",
            "golden_rule_summary": "Cash withdrawals moving money from bank ledger to physical cash.",
        },
    },
    {
        "id": 47,
        "rule_code": "GR47",
        "rule_title": "Debit Own Account Bank Transfers",
        "entry_type": "Debit",
        "rule_priority": 47,
        "description_tags": [
            "direct dr",
            "mob/friends/baiju suseelan nair/",
            "mob/own account/baiju suseelan nair/",
            "dep tfr",
            "sbinr52023070559034557",
            "/baiju suseelan nair/moblta",
            "transfer to 67093359418",
            "xx0049",
            "xx0049/pay to acc",
            "049sibl",
            "060sibl",
            "/sibl-xx081",
            "081sibl",
            "sibl-xx081",
            "wdl tfr inb imps",
            "own account/bai",
            "friends/baiju s",
            "internal account indiaide",
        ],
        "examples": ["Self bank transfer SBI to SIB"],
        "rule_metadata": {
            "category": "Transfer",
            "subcategory": "Self Inter-Account",
            "account_type": "None",
            "golden_rule_type": "Personal",
            "golden_rule_summary": "Outbound contra transfers between user's own bank accounts.",
        },
    },
    {
        "id": 59,
        "rule_code": "GR59",
        "rule_title": "Cash Deposit Inbound",
        "entry_type": "Credit",
        "rule_priority": 59,
        "description_tags": [
            "cash deposit beena",
            "cash deposit by beena",
            "beena cash deposit",
        ],
        "examples": ["Family cash deposit"],
        "rule_metadata": {
            "category": "Transfer",
            "subcategory": "Cash Deposits",
            "account_type": "None",
            "golden_rule_type": "Personal",
            "golden_rule_summary": "Inbound cash deposits into active bank accounts.",
        },
    },
    {
        "id": 65,
        "rule_code": "GR66",
        "rule_title": "UPI Digital Wallet Incoming Funds",
        "entry_type": "Credit",
        "rule_priority": 66,
        "description_tags": ["upi in", "upi in/", "upirev", "upi"],
        "examples": ["Digital wallet inbound transfer"],
        "rule_metadata": {
            "category": "Transfer",
            "subcategory": "Self Inter-Account",
            "account_type": "None",
            "golden_rule_type": "Personal",
            "golden_rule_summary": "Inbound wallet balances transferred into primary bank accounts.",
        },
    },
    {
        "id": 80,
        "rule_code": "GR47_CR",
        "rule_title": "Inbound Self Inter-Account Transfer",
        "entry_type": "Credit",
        "rule_priority": 47,
        "description_tags": ["transfer", "self transfer"],
        "examples": ["Inbound self account transfer"],
        "rule_metadata": {
            "category": "Transfer",
            "subcategory": "Self Inter-Account",
            "account_type": "None",
            "golden_rule_type": "Personal",
            "golden_rule_summary": "Inbound contra liquidity movement originating from another owned bank node.",
        },
    },
    {
        "id": 104,
        "rule_code": "GR104",
        "rule_title": "Director & Corporate Inbound/Outbound Loan Moves",
        "entry_type": "Debit",
        "rule_priority": 104,
        "description_tags": [
            "bluedot services pr",
            "bluedot",
            "loan from direc tor",
            "loan from director",
        ],
        "examples": ["Loan from director Bluedot Services"],
        "rule_metadata": {
            "category": "Liability",
            "subcategory": "Loans & Repayments",
            "account_type": "None",
            "golden_rule_type": "Personal",
            "golden_rule_summary": "Corporate and director loan balance movements.",
        },
    },
    # =========================================================================
    # 6. GR900 SERIES: DYNAMIC SUBCATEGORY NORMALIZATION & OVERRIDES
    # =========================================================================
    {
        "id": 901,
        "rule_code": "GR901",
        "rule_title": "Normalize Entertainment & Media Subcategory",
        "entry_type": "Debit",
        "rule_priority": 901,
        "description_tags": ["entertainment"],
        "examples": ["Entertainment subcategory override"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Entertainment & Media",
            "golden_rule_summary": "Map legacy entertainment subcategory to Entertainment & Media",
        },
    },
    {
        "id": 902,
        "rule_code": "GR902",
        "rule_title": "Normalize Food & Dining Subcategory",
        "entry_type": "Debit",
        "rule_priority": 902,
        "description_tags": ["food & beverages", "food and beverages"],
        "examples": ["Food & Beverages subcategory override"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Food & Dining",
            "golden_rule_summary": "Map legacy food & beverages subcategory to Food & Dining",
        },
    },
    {
        "id": 903,
        "rule_code": "GR903",
        "rule_title": "Normalize Personal & Family Subcategory",
        "entry_type": "Debit",
        "rule_priority": 903,
        "description_tags": [
            "family & personal",
            "personal expense",
            "personal expenses",
        ],
        "examples": ["Personal Expense subcategory override"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Personal & Family",
            "golden_rule_summary": "Map legacy personal expense subcategory to Personal & Family",
        },
    },
    {
        "id": 904,
        "rule_code": "GR904",
        "rule_title": "Normalize Hardware & Home Repairs Subcategory",
        "entry_type": "Debit",
        "rule_priority": 904,
        "description_tags": ["household"],
        "examples": ["Household subcategory override"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Hardware & Home Repairs",
            "golden_rule_summary": "Map legacy household subcategory to Hardware & Home Repairs",
        },
    },
    {
        "id": 905,
        "rule_code": "GR905",
        "rule_title": "Normalize Groceries & Shopping Subcategory",
        "entry_type": "Debit",
        "rule_priority": 905,
        "description_tags": ["shopping"],
        "examples": ["Shopping subcategory override"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Groceries & Shopping",
            "golden_rule_summary": "Map legacy shopping subcategory to Groceries & Shopping",
        },
    },
    {
        "id": 906,
        "rule_code": "GR906",
        "rule_title": "Normalize Fuel & Transport Subcategory",
        "entry_type": "Debit",
        "rule_priority": 906,
        "description_tags": ["travel & transport", "travel and transport"],
        "examples": ["Travel subcategory override"],
        "rule_metadata": {
            "category": "Expense",
            "subcategory": "Fuel & Transport",
            "golden_rule_summary": "Map legacy travel & transport subcategory to Fuel & Transport",
        },
    },
]


def run_seed():
    print("Starting Golden Accounting Rules seeding process...")
    active_rule_ids = set()

    try:
        with transaction.atomic():
            for item in GOLDEN_RULES_DATA:
                rule_id = item["id"]
                active_rule_ids.add(rule_id)

                # Upsert rule record directly
                rule_obj, created = AccountingRule.objects.update_or_create(
                    id=rule_id,
                    defaults={
                        "rule_code": item["rule_code"],
                        "rule_title": item["rule_title"],
                        "entry_type": item["entry_type"],
                        "rule_priority": item["rule_priority"],
                        "description_tags": item["description_tags"],
                        "examples": item["examples"],
                        "rule_metadata": item["rule_metadata"],
                        "is_active": 1,
                        "apply_to_ai": 0,
                    },
                )

                action_str = "Created" if created else "Updated"
                print(
                    f"  [✓] {action_str} Rule ID {rule_id}: {item['rule_code']} ({item['rule_title']})"
                )

            # Safely deactivate obsolete rules without triggering FK errors
            deactivated_count = AccountingRule.objects.exclude(
                id__in=active_rule_ids
            ).update(is_active=0)

            print(
                f"\nSuccessfully populated {len(GOLDEN_RULES_DATA)} active rules! "
                f"({deactivated_count} legacy rules deactivated)."
            )

    except Exception as e:
        logger.exception("Failed to execute rule book seeding")
        print(f"\n[✗] Seeding aborted due to error: {str(e)}")


if __name__ == "__main__":
    run_seed()
